### ISSUE TITLE
ebizzy test run error

### ISSUE THREAD

**Issue by Magnani95** [intel/lkp-tests#101]
Following to documentation passage to run the ebizzy test (lkp install, split-job, job install and job run; everything with sudo) cause the following output:
```
<path-to>/lkp-tests/monitors/turbostat: 12: cd: can't cd to /lkp/benchmarks/turbostat
<path-to>/lkp-tests/tests/ebizzy: 15: cd: can't cd to /lkp/benchmarks/ebizzy
```
If I create the two directory, then I get:
```
Iteration: 1
PWD: /lkp/benchmarks/ebizzy
2021-03-09 21:20:33 ./ebizzy -t 4 -S 10
/home/andrea/Documents/test-definitions/automated/linux/lkp/lkp-tests/tests/ebizzy: 21: ./ebizzy: not found
[repeated for 100 iteration]
```
I modified the script at `/home/andrea/Documents/test-definitions/automated/linux/lkp/lkp-tests/tests/ebizzy` to print the current directory, and as you can see, it's `/lkp/benchmarks/ebizzy`

I am on latest version of Ubuntu. I run hackbench test and it seems to run correctly.

**Comment by xilabao** [comment]
Hi @Magnani95  could you try the '-f' option of `lkp install` command ? 
e.g. `lkp install -f ./ebizzy-10s-100x-200%.yaml`

**Comment by Magnani95** [comment]
> Hi @Magnani95 could you try the '-f' option of `lkp install` command ?
> e.g. `lkp install -f ./ebizzy-10s-100x-200%.yaml`

Thank you, it worked
