### ISSUE TITLE
+0530 WARN -- Jobfile is a dirty file, better to run 'lkp split-job --compatible ./vm-scalability-300s-small-allocs.yaml' first

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#109]
Hi,
How to resolve below error?

> $ sudo lkp run ./vm-scalability-300s-small-allocs.yaml
> 2021-07-15 18:56:05 +0530 WARN -- Jobfile is a dirty file, better to run 'lkp split-job --compatible ./vm-scalability-300s-small-allocs.yaml' first

> $ sudo lkp split-job --compatible ./vm-scalability-300s-small-allocs.yaml
> /tmp/20210715-20631-szgfe9 => ./20210715-20631-szgfe9-300s-small-allocs.yaml

> $ sudo lkp run ./20210715-20631-szgfe9-300s-small-allocs.yaml
> 2021-07-15 18:56:37 +0530 WARN -- Jobfile is a dirty file, better to run 'lkp split-job --compatible ./20210715-20631-szgfe9-300s-small-allocs.yaml' first

Thanks

**Comment by xilabao** [comment]
Hi @Ankita-020696 , sorry about that, it should be fixed now, could you update the code and have a try?

**Comment by Ankita-020696** [comment]
> Hi @Ankita-020696 , sorry about that, it should be fixed now, could you update the code and have a try?

Working
Thanks
