### ISSUE TITLE
 +0530 WARN -- Jobfile is a dirty file, better to run 'lkp split-job --compatible ./chromeswap-5-uniform-0.25.yaml' first

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#114]
Hi 
could you check this?

$ lkp run ./chromeswap-5-uniform-0.25.yaml
2021-08-09 16:18:34 +0530 WARN -- Jobfile is a dirty file, better to run 'lkp split-job --compatible ./chromeswap-5-uniform-0.25.yaml' first

**Comment by xilabao** [comment]
@Ankita-020696  does this warning show with the latest code? I can't reproduce it, could you paste the full content of chromeswap-5-uniform-0.25.yaml?

**Comment by Ankita-020696** [comment]
> @Ankita-020696 does this warning show with the latest code? I can't reproduce it, could you paste the full content of chromeswap-5-uniform-0.25.yaml?

I was using old source, updated it.
Now its working.

Thanks
