### ISSUE TITLE
Add new benchmark to LKP

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#116]
Hi,
I am trying to add new benchmark to lkp. But after lkp run command getting following error.

Traceback (most recent call last):
	5: from /home/ankita/workspace/open_source/lkp-tests/bin/run-local:168:in `<main>'
	4: from /home/ankita/workspace/open_source/lkp-tests/lib/result_root.rb:380:in `convert_mrt'
	3: from /home/ankita/workspace/open_source/lkp-tests/lib/result_root.rb:338:in `convert_one_mresult_root'
	2: from /home/ankita/workspace/open_source/lkp-tests/lib/nresult_root.rb:317:in `new_node'
	1: from /home/ankita/workspace/open_source/lkp-tests/lib/nresult_root.rb:313:in `axes_to_table'
/home/ankita/workspace/open_source/lkp-tests/lib/nresult_root.rb:303:in `testcase_to_table': Unknow testcase: coremark (RuntimeError)

How do I fix this?

Thanks

**Comment by zhu1fei** [comment]
should add case info in  lib/stats.rb#LinuxTestcasesTableSet。

BTW: refer to :https://github.com/intel/lkp-tests/commit/bf8abb299
