### ISSUE TITLE
can‘t find directory：tools/perf ,while i install the atomic job

### ISSUE THREAD

**Issue by Desperatesonic** [intel/lkp-tests#12]
emmm, i am a greenhand, and i completely followed the reference to use lkp. After git clone lkp-test, make install, lkp install, split job,  I installed an atomic job--''./hackbench-50%-threads-socket.yaml'' . I could see from the command line that it showed 'making perf benchmark for centos'. after a while , it failed ,and showed that:
 "/root/lkp-tests/pack/perf: line 17: cd: tools/perf: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Making perf-LKP failed"

by the way , i am using tencent CVM , and there is some information here:

top - 22:38:14 up 2 days,  6:38,  1 user,  load average: 0.00, 0.01, 0.05
Tasks: 124 total,   1 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  0.0 sy,  0.0 ni, 99.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16267292 total, 14298988 free,   223200 used,  1745104 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 15689820 avail Mem 

I really need your help ,or I will be killed by my boss !!!   thanks for your time

**Comment by rli9** [comment]
thanks Desperatesonic for feedback, we will look into this asap.

**Comment by zhijianli88** [comment]
It's probably that it failed to clone the linux tree. could you share more log details.

**Comment by zhijianli88** [comment]
@Desperatesonic  if you already have a local linux tree, create a soft link under / like, which can tell lkp to use you local repo instead of cloning from web
```
lizhijian@haswell-OptiPlex-9020:/$ ls -al /linux -d
lrwxrwxrwx 1 root root 25 7月   9 09:27 /linux -> /home/lizhijian/lkp/linux
```

**Comment by Desperatesonic** [comment]
@zhijianli88  hello ，I am back. after 11 hours , a few seconds ago i try ' lkp install ./hackbench-50%-threads-socket.yaml ' again. and it shows some different log, I dont know whether it's ok now, and I feel very strange because between this 11 hours  I haven't done anything to it. 
          here is the log:

 Nothing to do
Making perf benchmark for centos
  BUILD:   Doing 'make -j8' parallel build
  HOSTCC   fixdep.o
  HOSTLD   fixdep-in.o
  LINK     fixdep
Warning: Kernel ABI header at 'tools/arch/powerpc/include/uapi/asm/unistd.h' differs from latest version at 'arch/powerpc/include/uapi/asm/unistd.h'
Warning: Kernel ABI header at 'tools/arch/x86/lib/memcpy_64.S' differs from latest version at 'arch/x86/lib/memcpy_64.S'

Auto-detecting system features:
...                         dwarf: [ OFF ]
...            dwarf_getlocations: [ OFF ]
...                         glibc: [ on  ]
...                          gtk2: [ OFF ]
...                      libaudit: [ on  ]
...                        libbfd: [ on  ]
...                        libelf: [ OFF ]
...                       libnuma: [ on  ]
...        numa_num_possible_cpus: [ on  ]
...                       libperl: [ OFF ]
...                     libpython: [ OFF ]
...                      libslang: [ OFF ]
...                     libcrypto: [ OFF ]
...                     libunwind: [ OFF ]
...            libdw-dwarf-unwind: [ OFF ]
...                          zlib: [ on  ]
...                          lzma: [ on  ]
...                     get_cpuid: [ on  ]
...                           bpf: [ on  ]

Makefile.config:317: No libelf found. Disables 'probe' tool, jvmti and BPF support in 'perf record'. Please install libelf-dev, libelf-devel or elfutils-libelf-devel
Makefile.config:444: No sys/sdt.h found, no SDT events are defined, please install systemtap-sdt-devel or systemtap-sdt-dev
Makefile.config:517: Disabling post unwind, no support found.
Makefile.config:582: No libcrypto.h found, disables jitted code injection, please install libssl-devel or libssl-dev
Makefile.config:597: slang not found, disables TUI support. Please install slang-devel, libslang-dev or libslang2-dev
Makefile.config:611: GTK2 not found, disables GTK2 support. Please install gtk2-devel or libgtk2.0-dev
Makefile.config:638: Missing perl devel files. Disabling perl scripting support, please install perl-ExtUtils-Embed/libperl-dev
Makefile.config:670: No 'python-config' tool was found: disables Python support - please install python-devel/python-dev
Makefile.config:813: No libbabeltrace found, disables 'perf data' CTF format support, please install libbabeltrace-dev[el]/libbabeltrace-ctf-dev

..
Installing perf-LKP
Just make /lkp/benchmarks/perf-x86_64.cgz
Use: /root/lkp-tests/distro/installer/centos install binutils audit-libs-devel binutils-devel bison flex libdwarf-devel libunwind-devel numactl-devel xz-devel zlib-devel 
Loaded plugins: fastestmirror, langpacks
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Package binutils-2.27-28.base.el7_5.1.x86_64 already installed and latest version
Package audit-libs-devel-2.8.1-3.el7.x86_64 already installed and latest version
Package binutils-devel-2.27-28.base.el7_5.1.x86_64 already installed and latest version
Package bison-3.0.4-1.el7.x86_64 already installed and latest version
Package flex-2.5.37-3.el7.x86_64 already installed and latest version
Package libdwarf-devel-20130207-4.el7.x86_64 already installed and latest version
Package 2:libunwind-devel-1.2-2.el7.x86_64 already installed and latest version
Package numactl-devel-2.0.9-7.el7.x86_64 already installed and latest version
Package xz-devel-5.2.2-1.el7.x86_64 already installed and latest version
Package zlib-devel-1.2.7-17.el7.x86_64 already installed and latest version
Nothing to do
Making perf benchmark for centos
perf is already installed into /lkp/benchmarks/perf, skip this packing
Installing perf-LKP
Just make /lkp/benchmarks/perf-x86_64.cgz
Making turbostat benchmark for centos
timeout 60m git clone -q https://github.com/aaronlu/turbostat.git turbostat
gcc -Wall turbostat.c -c -o /tmp/build-turbostat/turbostat/turbostat.o
gcc  turbostat.o -lrt -o /tmp/build-turbostat/turbostat/turbostat
Installing turbostat-LKP
Just make /lkp/benchmarks/turbostat-x86_64.cgz


that's all about the log ,and I want to know what do you mean about local linux tree, how do I know I already have one ,and how to create a soft link..... I am so foolish , please help me, dear zhijianli

**Comment by zhijianli88** [comment]
check whether perf is installed successfully, below is a good example
```
[root@centos-lkp hackbench]# ls /lkp/benchmarks/perf/
perf
```
if perf have been installed, you can go ahead, lkp run xxx.yaml like
```
[root@centos-lkp hackbench]# lkp run ./hackbench-50%-threads-socket.yaml
2018-07-08 23:17:19 /usr/local/bin/hackbench -g 2 --threads -l 60000
Running in threaded mode with 2 groups using 40 file descriptors each (== 80 tasks)
Each sender will pass 60000 messages of 100 bytes
```

**Comment by Desperatesonic** [comment]
@zhijianli88 thank you so much for your help，I already make sure there is “/lkp/benchmarks/perf/” ， but when I run "lkp run ./hackbench-50%-threads-socket.yaml" , new error comes out: 

2018-07-09 10:33:25 /usr/local/bin/hackbench -g 4 --threads -l 60000
Running in threaded mode with 4 groups using 40 file descriptors each (== 160 tasks)
Each sender will pass 60000 messages of 100 bytes
Time: 23.483
kill 1501 vmstat --timestamp -n 10 
kill 1489 dmesg --follow --decode 
kill 1584 mpstat 1 
kill 1504 vmstat --timestamp -n 1 
wait for background monitors: 1493 1525 15581521 1528 1549 1532 1577 1572 1537 uptime proc-stat diskstats proc-vmstat meminfo softirqs slabinfo sched_debug turbostat interrupts
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:52 ERROR -- /root/lkp-tests/sbin/dump-stat hackbench  exit code 1, check /dev/shm/lkp-stats.PuUIpw4M
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:52 ERROR -- /root/lkp-tests/sbin/dump-stat kmsg  exit code 1, check /dev/shm/lkp-stats.KXdjS1eR
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:52 ERROR -- /root/lkp-tests/sbin/dump-stat uptime  exit code 1, check /dev/shm/lkp-stats.1qWnJ95G
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:53 ERROR -- /root/lkp-tests/sbin/dump-stat vmstat  exit code 1, check /dev/shm/lkp-stats.mPLuHlp0
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:53 ERROR -- /root/lkp-tests/sbin/dump-stat proc-vmstat  exit code 1, check /dev/shm/lkp-stats.5pI056yi
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:53 ERROR -- /root/lkp-tests/sbin/dump-stat meminfo  exit code 1, check /dev/shm/lkp-stats.F34Rsv8T
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:54 ERROR -- /root/lkp-tests/sbin/dump-stat slabinfo  exit code 1, check /dev/shm/lkp-stats.cSrS1a3I
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:55 ERROR -- /root/lkp-tests/sbin/dump-stat interrupts  exit code 1, check /dev/shm/lkp-stats.93sntXLc
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:55 ERROR -- /root/lkp-tests/sbin/dump-stat softirqs  exit code 1, check /dev/shm/lkp-stats.fdZiuGmX
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:55 ERROR -- /root/lkp-tests/sbin/dump-stat diskstats  exit code 1, check /dev/shm/lkp-stats.jlUkHJ1J
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:55 ERROR -- /root/lkp-tests/sbin/dump-stat sched_debug  exit code 1, check /dev/shm/lkp-stats.9aq0uUqf
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:56 ERROR -- /root/lkp-tests/sbin/dump-stat mpstat  exit code 1, check /dev/shm/lkp-stats.LLCIvQeI
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:56 ERROR -- /root/lkp-tests/sbin/dump-stat time  exit code 1, check /dev/shm/lkp-stats.gYYdOM6d
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:56 ERROR -- /root/lkp-tests/sbin/dump-stat time  exit code 1, check /dev/shm/lkp-stats.uNJozlpP
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:56 ERROR -- /root/lkp-tests/sbin/dump-stat dmesg  exit code 1, check /dev/shm/lkp-stats.pnP1oVln
/root/lkp-tests/sbin/dump-stat:49:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)
2018-07-09 10:33:56 ERROR -- /root/lkp-tests/sbin/dump-stat kmsg  exit code 1, check /dev/shm/lkp-stats.PaKqguXM


there are so many NoMethodErrors . which step I made mistake? or maybe this is a unfixable problem?

**Comment by zhijianli88** [comment]
could you mind to upgrade the ruby to 2.3 or later : https://tecadmin.net/install-ruby-previous-stable-centos/
```
[root@centos-lkp ~]# rvm install 2.3
Warning, new version of rvm available '1.29.4', you are using older version '1.29.3'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/centos/7/x86_64/ruby-2.3.4.tar.bz2
Checking requirements for centos.
Requirements installation successful.
ruby-2.3.4 - #configure
ruby-2.3.4 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.2M  100 25.2M    0     0  50577      0  0:08:43  0:08:43 --:--:-- 51531
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.4 - #validate archive
ruby-2.3.4 - #extract
ruby-2.3.4 - #validate binary
ruby-2.3.4 - #setup
ruby-2.3.4 - #gemset created /usr/local/rvm/gems/ruby-2.3.4@global
ruby-2.3.4 - #importing gemset /usr/local/rvm/gemsets/global.gems..............................
ruby-2.3.4 - #generating global wrappers........
ruby-2.3.4 - #gemset created /usr/local/rvm/gems/ruby-2.3.4
ruby-2.3.4 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.4 - #generating default wrappers........
[root@centos-lkp ~]# rvm list

rvm rubies

=* ruby-2.3.4 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

[root@centos-lkp ~]# rvm use 2.3.4 --default
Using /usr/local/rvm/gems/ruby-2.3.4
[root@centos-lkp ~]# ruby --version
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
```
and install and run lkp again
```
[root@centos-lkp hackbench]# lkp install ./hackbench-50%-threads-socket.yaml
[root@centos-lkp hackbench]# lkp run ./hackbench-50%-threads-socket.yaml
```

**Comment by Desperatesonic** [comment]
@zhijianli88 Thank you so much，it seems alright and i can survive from my boss。here is my last question ：how can I know about those detail’s meaning ，such as ‘softirqs.CPU2.TIMER": 2340202,’, ofcourse I know about softirqs or cpu or timer , But I dont know what's the number's meaning and what is the Unit(单位).  and there is a lot of Abbreviations,  where can I find more reference , and everytime I run the yaml, will it tell me my detailed configuration in some json?

**Comment by zhijianli88** [comment]
Congratulation, you are so cute :)
lkp-tests will format all raw ouputs to json which is easy to be understood by lkp.
Actually, i'm not clear to all as well,  you can check the raw output if you want to know more details.


> will it tell me my detailed configuration in some json?

the details are recorded at $result/job.yaml which contains you host info, job parameters etc.
