### ISSUE TITLE
Split Job appears broken

### ISSUE THREAD

**Issue by lsgunth** [intel/lkp-tests#129]
With the latest master branch, trying to reproduce a test fails on the split-job test:

```
bin/lkp split-job --compatible job.yaml
Traceback (most recent call last):
	3: from kp-tests/sbin/split-job:95:in `<main>'
	2: from lkp-tests/sbin/split-job:95:in `each'
	1: from kp-tests/sbin/split-job:98:in `block in <main>'
lkp-tests/lib/job.rb:202:in `load': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

This seems to have been introduced in 9e624cd599f54 as checking out before that commit seems to work fine.

I'm running on a Debian Bullseye system with ruby 2.7.4p191

**Comment by Yujie-Liu** [comment]
Hi @lsgunth , sorry for the inconvenience. We did some code refactoring recently and caused this bug. It has been fixed now. Please kindly pull the latest master branch to rerun the test, thanks.

**Comment by lsgunth** [comment]
Thanks! It seems to be fixed today.
