### ISSUE TITLE
unixbench: install issue on ubuntu-20.04 and ubuntu-21.04

### ISSUE THREAD

**Issue by bssrikanth** [intel/lkp-tests#136]
ubuntu21.04 and ubuntu 20.04 repos seem to contain perl-modules-5.32 and perl-modules-5.30 instead of perl-modules-5.26 which is what unixbench dependencies try to install via lkp install. Similarly  ubuntu21.04 and ubuntu 20.04 repos seem to contain libperl5.32 and libperl5.30 instead of libperl5.26 which is currently present in distro/adaptation/ubuntu.

I tried removing version information from these two packages distro/adaptation/ubuntu,thinking it would pick latest available version of the packages, but that does not seem to work incase of libperl. Since same adaptation file is used in case of both ubuntu versions, if I change the version for one release another release seem to fail.

**Comment by Yujie-Liu** [comment]
@bssrikanth We have updated the adaptation files for ubuntu 20.04 and 21.04, would you mind give a try on the latest code base? thanks.

**Comment by bssrikanth** [comment]
Thanks @Yujie-Liu , have tested with latest version and things works as expected. Closing.
