### ISSUE TITLE
outdated info and releases for some net test packages

### ISSUE THREAD

**Issue by xosevp** [intel/lkp-tests#142]
* nuttcp (latest 8.2.2):
url: http://nuttcp.org
source: http://nuttcp.org/nuttcp/
* netpipe (latest 5.1.4, fixes in https://gitlab.beocat.ksu.edu/daveturner/netpipe-5.x repo):
url: https://netpipe.cs.ksu.edu
source: https://netpipe.cs.ksu.edu/download/
* netperf (latest 2.7.0, fixes in git repo):
url: https://hewlettpackard.github.io/netperf/
source: https://github.com/HewlettPackard/netperf/tags

**Comment by care101** [comment]
thanks, but can't access 'https://netpipe.cs.ksu.edu', could you offer another link to get latest version of netpipe?

> * netpipe (latest 5.1.4, fixes in https://gitlab.beocat.ksu.edu/daveturner/netpipe-5.x repo):
>   url: https://netpipe.cs.ksu.edu
>   source: https://netpipe.cs.ksu.edu/download/

**Comment by xosevp** [comment]
I do not have any problem with it.
https://netpipe.cs.ksu.edu/ is up and online.

You can see it at:
https://web.archive.org/web/20210501032326/https://netpipe.cs.ksu.edu/
https://archive.ph/DgExb


There is a mirror at https://fossies.org/ :
https://fossies.org/linux/privat/NetPIPE-5.1.4.tar.gz/

**Comment by care101** [comment]
@xosevp sorry for the late response, we have updated the repo and used the latest version. Thanks!

- nuttcp
ver: 8.2.2
url: http://nuttcp.org/nuttcp
source: http://nuttcp.org/nuttcp/nuttcp-8.2.2/bin/nuttcp-8.2.2.fc32.x86_64
- netpipe
ver: 5.1.4
url: https://fossies.org/linux/privat/NetPIPE-5.1.4.tar.gz
source: https://fossies.org/linux/privat/NetPIPE-5.1.4.tar.gz
- netperf
ver: 2.7.0
url: https://github.com/HewlettPackard/netperf
source: https://github.com/HewlettPackard/netperf/archive/netperf-2.7.0.tar.gz
