### ISSUE TITLE
local lkp runs are failing

### ISSUE THREAD

**Issue by bssrikanth** [intel/lkp-tests#144]
When I try to run lkp locally, its failing with below error:
```
# lkp run ./hackbench-pipe-8-process-50%.yaml
Traceback (most recent call last):
        6: from /home/LKP/lkp-tests/bin/run-local:137:in `<main>'
        5: from /home/LKP/lkp-tests/lib/job.rb:691:in `expand_params'
        4: from /home/LKP/lkp-tests/lib/job.rb:78:in `for_each_in'
        3: from /home/LKP/lkp-tests/lib/job.rb:78:in `each'
        2: from /home/LKP/lkp-tests/lib/job.rb:79:in `block in for_each_in'
        1: from /home/LKP/lkp-tests/lib/job.rb:694:in `block in expand_params'
/home/LKP/lkp-tests/lib/job.rb:666:in `run_filter': uninitialized constant Job::Bash (NameError)
```
Local runs were working fine when I ran tests a week back, this issue seems to be a regression.

**Comment by bssrikanth** [comment]
I hit above issue while running ebizzy/hackbench.. but unixbench seems running fine locally.

**Comment by bssrikanth** [comment]
This failure is not seen with all benchmarks.. ebizzy/hackbench seems hitting this issue.. not unixbench.. will be adding more details as and when I find things while debugging issue.. if you have any hints on failure please share.

**Comment by Yujie-Liu** [comment]
Hi @bssrikanth, sorry for the inconvenience. We did some code cleanup recently which unfortunately led to this regression. It needs to have a `require "#{LKP_SRC}/lib/bash"` in lib/job.rb. We'll fix it ASAP.

**Comment by bssrikanth** [comment]
Thank for quick update @Yujie-Liu . 
Update from my debugging, thought it might help: On my setup I reverted to commit 57a1ac0cf29c7567d3076c5c885f35525c275935, where I do not hit this issue.

**Comment by bssrikanth** [comment]
> Thank for quick update @Yujie-Liu . Update from my debugging, thought it might help: On my setup I reverted to commit [57a1ac0](https://github.com/intel/lkp-tests/commit/57a1ac0cf29c7567d3076c5c885f35525c275935), where I do not hit this issue.

I just saw https://github.com/intel/lkp-tests/commit/978bc576b930af6868f531eabdf77e8392a81149 .. thank you,I will test that and get back here.
