### ISSUE TITLE
lkp run on RHEL 9 hitting issues

### ISSUE THREAD

**Issue by bssrikanth** [intel/lkp-tests#185]
On RHEL9, when ever I run lkp benchmarks I see below error at the end of the run [which is not the case with RHEL 8.x]:
```
/home/lkp-tests/lib/data_store.rb:62:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /home/lkp-tests/lib/common.rb:24:in `new'
        from /home/lkp-tests/lib/common.rb:24:in `block in add_cached_method'
        from /home/lkp-tests/lib/data_store.rb:246:in `create_new'
        from /home/lkp-tests/lib/nresult_root.rb:241:in `create_layout'
        from /home/lkp-tests/lib/nresult_root.rb:337:in `create_tables_layout'
        from /home/lkp-tests/bin/run-local:168:in `<main>'
```
I have tried removing the whole directory "/lkp/data/mresult_root/" and have rerun, hitting same issue on RHEL 9. Any other possible solutions please let me know.

**Comment by rli9** [comment]
Hi Srikanth, this could be related to ruby version, the code works in ruby 2.5. Can you share the version on rhel 9? We will think of this for how to support a different version.

**Comment by bssrikanth** [comment]
@rli9 RHEL 9 seem to come with `ruby 3.0.4p208` where as RHEL 8.x has `ruby 2.5.9p229`

**Comment by rli9** [comment]
hi @bssrikanth, can you give a try to see whether the issue still exists? I'm not sure whether other places will be impacted due to ruby version, if any, we will follow up to address.

**Comment by bssrikanth** [comment]
> hi @bssrikanth, can you give a try to see whether the issue still exists? I'm not sure whether other places will be impacted due to ruby version, if any, we will follow up to address.

Hi @rli9 with latest code I am not seeing the issue. Thank you.
