### ISSUE TITLE
stress-ng/os-performance-1HDD-ext4-10%-inode-flags-60s: all bogo-op counters are zero, data may be incorrect

### ISSUE THREAD

**Issue by jie2xzhou** [intel/lkp-tests#201]
ops is 0 in test.

$ stress-ng --timeout 60 --times --verify --metrics-brief --inode-flags 9
stress-ng: info:  [180930] setting to a 60 second run per stressor
stress-ng: info:  [180930] dispatching hogs: 9 inode-flags
stress-ng: info:  [180930] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s
stress-ng: info:  [180930]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
stress-ng: info:  [180930] inode-flags           0     60.15      0.00      0.00         0.00           0.00
stress-ng: info:  [180930] for a 60.30s run time:
stress-ng: info:  [180930]     361.79s available CPU time
stress-ng: info:  [180930]       0.36s user time   (  0.10%)
stress-ng: info:  [180930]      16.19s system time (  4.47%)
stress-ng: info:  [180930]      16.55s total time  (  4.57%)
stress-ng: info:  [180930] load average: 30.13 9.01 3.28
stress-ng: info:  [180930] successful run completed in 60.30s (1 min, 0.30 secs)

**Comment by zhoujie2022** [comment]
commit 6a83be1933fff7f0b934c22350c8c73e82404580
Author: Jie2x Zhou <jie2x.zhou@intel.com>
Date:   Wed Jan 18 16:17:20 2023 +0800

    jobs/stress-ng: comment out non workable inode-flags
    
    To avoid warn metrics-check: all bogo-op counters are zero, data may be incorrect
    
    All inode-flags testcase in v5.19 v6.0 v6.1 v6.2-rc3 kernel ops is 0.
    So comment out inode-flags to avoid this warning.
    
    output:
    2023-01-18 08:00:47 stress-ng --timeout 60 --times --verify --metrics-brief --inode-flags 9
    stress-ng: info:  [5371] setting to a 60 second run per stressor
    stress-ng: info:  [5371] dispatching hogs: 9 inode-flags
    stress-ng: info:  [5371] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s
    stress-ng: info:  [5371]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
    stress-ng: info:  [5371] inode-flags           0     60.06      0.53     90.53         0.00           0.00
    stress-ng: warn:  [5371] metrics-check: all bogo-op counters are zero, data may be incorrect

**Comment by rli9** [comment]
thanks for the patch
