### ISSUE TITLE
fio-basic/4k-performance-1SSD-xfs-io_uring_cmd-8t-300s-read-256g: stderr: ioengine io_uring_cmd only works with nvme ns generic char devices (/dev/ngXnY)

### ISSUE THREAD

**Issue by jie2xzhou** [intel/lkp-tests#202]
error:
ioengine io_uring_cmd only works with nvme ns generic char devices (/dev/ngXnY)

have /dev/ngXnY device.
[root@fedoraguest1 ~]# cat /etc/redhat-release
Fedora release 37 (Thirty Seven)
[root@fedoraguest1 ~]# ls /dev/nvme*
/dev/nvme0  /dev/nvme0n1
[root@fedoraguest1 ~]# ls /dev/ng*
/dev/ng0n1

Maybe should use /dev/ng0n1 instead of /dev/nvme0n1p2.
cat ./lkp/result/fio.task
[global]
bs=4k
ioengine=io_uring_cmd
iodepth=32
size=34359738368
nr_files=1
filesize=34359738368
direct=0
runtime=300
invalidate=1
fallocate=posix
io_size=34359738368
file_service_type=roundrobin
random_distribution=random
group_reporting
pre_read=0
[task_0]
rw=read
directory=/fs/nvme0n1p2
numjobs=8

**Comment by zhoujie2022** [comment]
commit 1c0f2ccde14bbbd008f1eed22b788beadb052dc1
Author: Jie2x Zhou <jie2x.zhou@intel.com>
Date:   Wed Jan 18 13:51:26 2023 +0800

    jobs/fio-basic: comment out io_uring_cmd as it only works with nvme ns generic char devices (/dev/ngXnY)
    
    Error:
    ioengine io_uring_cmd only works with nvme ns generic char devices (/dev/ngXnY)
    
    Error occurred in all io_uring_cmd test.
    Error occurred in kernel from v5.16 to v6.2-rc4.
    
    Reason:
    io_uring_cmd only works with NVMe character device (/dev/ngXnY).
    https://github.com/axboe/fio/blob/master/HOWTO.rst
            **io_uring_cmd**
                    Fast Linux native asynchronous I/O interface for NVMe pass
                    through commands. This only works with NVMe character device
                    (/dev/ngXnY).
    
    /dev/ngXnY is added in v5.12.
    commit 2637baed78010eeaae274feb5b99ce90933fadfb
    Author: Minwoo Im <minwoo.im.dev@gmail.com>
    Date:   Wed Apr 21 16:45:04 2021 +0900    nvme: introduce generic per-namespace chardev
        The chardev naming convention will similar to the existing blkdev naming,
        using a ng prefix instead of nvme, i.e.
                - /dev/ngXnY
    
    now test program use /dev/nvme0n1p2 instead of /dev/ng0n1.
    So this error occurred.
    Maybe support /dev/ng0n1 in future.

**Comment by rli9** [comment]
thanks for the patch
