### ISSUE TITLE
enable uperf test suite

### ISSUE THREAD

**Issue by jie2xzhou** [intel/lkp-tests#205]
https://github.com/uperf/uperf
http://uperf.org/
https://lore.kernel.org/all/a49ea23a-998e-2282-4c93-5c6c94f2c28d@linux.intel.com/

**Comment by zhoujie2022** [comment]
refer netperf to implement uperf test.
refer to programs/hackbench dir, put similar files under programs dir like what hackbench is organized now.

**Comment by zhoujie2022** [comment]
1. Install
apt install -y autoconf libsctp-dev

2. Compile
git clone https://github.com/uperf/uperf.git
cd uperf
autoreconf --install && ./configure && make
  +------------------------------------------------+
  | Supported Protocols:                           |
  |                 TCP:  yes                      |
  |                 UDP:  yes                      |
  |                 RDS:   no                      |
  |                 SSL:   no                      |
  |                SCTP:  yes                      |
  |               VSOCK:  yes                      |
  +------------------------------------------------+
  |Network stats collection enabled?:           yes|
  |        CPU Performance counters?:   Not enabled|
  +------------------------------------------------+
note: 
           "RDS" and "SSL" and "CPU Performance counters " is disabled as default.
           run "./configure --enable-ssl --enable-rds" can enable RDS and SSL.
           " CPU Performance counters" enable need libcpc(https://github.com/kralf/libcpc).

3. Run
  ./src/uperf -s &
  export h=127.0.0.1
  export proto=TCP
  ./src/uperf -m ./workloads/netperf.xml

4. Output
Starting 1 threads running profile:netperf ...   0.00 seconds
Txn1            0 /   1.00(s) =            0           1op/s                                                         
Txn2      259.89M /  30.23(s) =    72.11Mb/s      100153op/s                                                         
Txn3            0 /   0.00(s) =            0           0op/s                                                         
---------------------------------------------------------------------------------------------------------------------
Total     259.89M /  32.34(s) =    67.42Mb/s       93638op/s 

Netstat statistics for this run
---------------------------------------------------------------------------------------------------------------------
Nic       opkts/s     ipkts/s      obits/s      ibits/s
lo          93638       93638   106.37Mb/s   106.37Mb/s 
ens1            2           2     4.65Kb/s     1.21Kb/s 
---------------------------------------------------------------------------------------------------------------------

Run Statistics
Hostname            Time       Data   Throughput   Operations      Errors
---------------------------------------------------------------------------------------------------------------------
127.0.0.1         32.34s   259.89MB    67.42Mb/s      3027910        0.00
master            32.34s   259.89MB    67.42Mb/s      3027910        0.00
---------------------------------------------------------------------------------------------------------------------
Difference(%)     -0.00%      0.00%        0.00%        0.00%       0.00%
