### ISSUE TITLE
Feature: Merge results from different machines

### ISSUE THREAD

**Issue by schrht** [intel/lkp-tests#23]
https://github.com/intel/lkp-tests/issues/20#issuecomment-425630411

Please consider to add a feature for `lkp ncompare` to deal with the results from different machines. Thanks!

**Comment by bssrikanth** [comment]
Is there any action taken against this request? its one of the useful feature for us.

**Comment by rli9** [comment]
Sorry for late update, we will work on this soon and provide update to you next week.

**Comment by bssrikanth** [comment]
thank you @rli9

**Comment by bssrikanth** [comment]
Adding more details:

Currently I have run LKP ebizzy benchmarks on two different machines. And have aggregated the results on one of the servers.

`lkp result ebizzy` is able to detect results copied. dellj853host and dellj853host are the two different hosts.

```
# lkp result ebizzy
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/0/
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/1/
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/2/
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/3/
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.15.2-v5.15/0/
/lkp/result/ebizzy/10s-100x-200%/dellj853host/rhel/defconfig/gcc/5.15.2-v5.15/1/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/0/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/1/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/2/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/3/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/4/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.14.6-v5.14/5/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-build40/0/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-build41/0/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-build41/1/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-v5.15/0/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-v5.15/1/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-v5.15/2/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-v5.15/3/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.15.2-v5.15/4/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.16.2-v5.16/0/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.16.2-v5.16/1/
/lkp/result/ebizzy/10s-100x-200%/delll853host/rhel/defconfig/gcc/5.17.0-rc3-v5.17-rc3/0/
/lkp/result/ebizzy/10s-5x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/0/
/lkp/result/ebizzy/10s-5x-200%/dellj853host/rhel/defconfig/gcc/5.14.6-v5.14/1/
/lkp/result/ebizzy/10s-5x-200%/dellj853host/rhel/defconfig/gcc/5.15.2-v5.15/0/
/lkp/result/ebizzy/10s-5x-200%/dellj853host/rhel/defconfig/gcc/5.15.2-v5.15/1/
```

`lkp ncompare` seems not supporting comparison of results from aggregated results pool containing results from 2 hosts.

![image](https://user-images.githubusercontent.com/11852063/154405833-735444b1-a0be-40f0-ab85-e1048929f670.png)

Hope this is same enhancement addressed as part of this issue. Thank you.

**Comment by xilabao** [comment]
@bssrikanth  we have added a new tool to handle this, please see https://github.com/intel/lkp-tests/commit/70956cd0ef259ead1ba1a060fa7689f915a74cad

**Comment by bssrikanth** [comment]
@xilabao thank you!!, will give it a try and get back here.

**Comment by bssrikanth** [comment]
@xilabao can you please post more generic examples parameters to be used with this tool? the examples in commit message are bit confusing to me, it would be good if you can callout the parameters more generically. 
Secondly I do not see `lkp` help showing help message this new tool, I think thats something being already worked on.

**Comment by xilabao** [comment]
> can you please post more generic examples parameters to be used with this tool? 
@bssrikanth can you share more details from your side? so we can consider to support more cases in the tool.  

> the examples in commit message are bit confusing to me
sorry about that, which part make you confused?

> callout the parameters more generically
sure,  a pull request to the repo is also welcome.
 
> I do not see lkp help showing help message this new tool
It depends, if not many people use this tool, we may not list it in the help message, as the last line said:
"More commands can be found in /home/xxx/code/lkp/lkp-src/{bin,sbin,tools}/"

**Comment by bssrikanth** [comment]
@xilabao I am looking for getting ncompare results from the aggregated pool of result from multiple hosts. More details are at https://github.com/intel/lkp-tests/issues/23#issuecomment-1042567919. With this new tool can you please let me know parameters to pass to lkp ncompare?

**Comment by xilabao** [comment]
@bssrikanth 
1. if you already copied the results to the local host
please run `lkp merge LOCAL_RESULT_DIR` , e.g. `lkp merge /lkp/result/ebizzy/10s-5x-200%/dellj853host`

2. if not
 please run `lkp merge -r REMOTE_HOSTANEM REMOTE_RESULT_DIR `, it will run `rsync` command to copy results to local host and add results to local database.

**Comment by bssrikanth** [comment]
> @bssrikanth
> 
> 1. if you already copied the results to the local host
>    please run `lkp merge LOCAL_RESULT_DIR` , e.g. `lkp merge /lkp/result/ebizzy/10s-5x-200%/dellj853host`
> 2. if not
>    please run `lkp merge -r REMOTE_HOSTANEM REMOTE_RESULT_DIR `, it will run `rsync` command to copy results to local host and add results to local database.

@xilabao thanks for the quick reply. Sure I will give this a try and get back here.

**Comment by bssrikanth** [comment]
> > @bssrikanth
> > 
> > 1. if you already copied the results to the local host
> >    please run `lkp merge LOCAL_RESULT_DIR` , e.g. `lkp merge /lkp/result/ebizzy/10s-5x-200%/dellj853host`
> > 2. if not
> >    please run `lkp merge -r REMOTE_HOSTANEM REMOTE_RESULT_DIR `, it will run `rsync` command to copy results to local host and add results to local database.
> 
> @xilabao thanks for the quick reply. Sure currently I was using the test machines for another test, I will give this a try and get back here in sometime today

I reran few tests across machines, this time I used merge option [not manually copy as I did previous time] and then ncompare works good. I am in process of running few other scenarios which could be part of our usecases, will update the results once those are done.

**Comment by bssrikanth** [comment]
@xilabao @rli9 update: I ran various test scenarios covering multiple test machines, multiple benchmarks, multiple distros. Using the new merge tool I am able to aggregate and parse results as expected. Thank you.

**Comment by rli9** [comment]
Thanks @bssrikanth, I will close the issue, and if there's new request, feel free to raise it.
