### ISSUE TITLE
pm-qa: re-organize to be under programs

### ISSUE THREAD

**Issue by rli9** [intel/lkp-tests#239]
Refer to d7206025f284 as example. Also add meta.yaml for pm-qa.

### Acceptance Test
* The components of test is moved to programs
* Refer to lkp-tests/docker/README.md, docker build needs to be done for only once to create a base docker image, then follow the “Run one atomic job” section to go through “lkp split-job”, “lkp install”, “lkp run”, “lkp result” steps.
* Once “lkp result” command can show a good result path with expected result files in it, we judge this as a good re-organization and accept it. e.g.
```
root@lkp-docker:/lkp/lkp-tests# lkp rt hackbench
/lkp/result/hackbench/pipe-8-process-1600%/lkp-docker/debian/defconfig/gcc-8/5.15.0-60-generic/0/

[root@lkp-docker:/lkp/result/hackbench/pipe-8-process-1600%/lkp-docker/debian/defconfig/gcc-8/5.15.0-60-generic/0#](mailto:root@lkp-docker:/lkp/result/hackbench/pipe-8-process-1600%25/lkp-docker/debian/defconfig/gcc-8/5.15.0-60-generic/0#) ls
bdi_dev_mapping  hackbench.json       matrix.csv       post-run.perf-profile  slabinfo.json.gz  uptime
bg-procs-debug   hackbench.time       matrix.json.gz   post-run.perf-sched    softirqs.gz       uptime.json
cpufreq-stats    hackbench.time.json  meminfo.gz       proc-stat.gz           softirqs.json     vmstat
cpuidle          heartbeat            meminfo.json.gz  proc-vmstat.gz         stats.csv         vmstat.json.gz
cpuidle.json     interrupts.gz        mpstat           proc-vmstat.json.gz    stats.json
diskstats.gz     interrupts.json      mpstat.json.gz   program_list           time
diskstats.json   job.sh               mpstat_update    reproduce.sh           time.json
hackbench        job.yaml             perf-stat.gz     slabinfo               turbostat
```

**Comment by howardthuang** [comment]
Working on this.

**Comment by howardthuang** [comment]
Having trouble finding a description for the pm-qa test, other than it is for power management testing.  The git repository for pm-qa only has links to a blank wiki page and not much documentation.  Not sure what to put in the meta.yaml.
