### ISSUE TITLE
spec: check the config format in include/ dir

### ISSUE THREAD

**Issue by rli9** [intel/lkp-tests#241]
Add a rspec test to validate the config format for need_kconfig part, which should
- not start with CONFIG_
- only contain n, m, y or nothing
- only contain i386, x86_64 or nothing

### Reference
https://github.com/intel/lkp-tests/wiki/Coding-Standard#rspec-test

**Comment by weishan18** [comment]
hi @rli9, I would like to know is it to add the test in lkp-tests/spec/filter_need_kconfig_spec.rb?

**Comment by weishan18** [comment]
Also, would like to know for
need_kconfig: NFS_V3
is the NFS_V3 considered in a correct format?

**Comment by rli9** [comment]
> is the NFS_V3 considered in a correct format?
yes, the kernel config is CONFIG_NFS_V3. In the include side, CONFIG_ prefix is removed.

**Comment by rli9** [comment]
> hi @rli9, I would like to know is it to add the test in lkp-tests/spec/filter_need_kconfig_spec.rb?

The initial idea is to have a separated spec to cover this issue, to mainly focus on the format correctness of need_kconfig section.

**Comment by weishan18** [comment]
May I get more explanation on the need_konfig section? 
Thank you very much!

**Comment by rli9** [comment]
> May I get more details/explanation on the need_konfig section you referring to?

It basically means to enable these kconfigs for kernel in order to run the test successfully or allow more functionalities of test being enabled. 

Take blktests for example, to run nvme test group, it is meaningful only when NVME related configs are enabled in kernel.
```
need_kconfig:
% if ___.test =~ /nvme/
- NVME_MULTIPATH: y
- NVME_TARGET: m
- NVME_TARGET_LOOP: m
% elsif ___.test =~ /srp/
- INFINIBAND: m
- INFINIBAND_IPOIB: m
- INFINIBAND_SRP: m
```

So this is test by test, you can use it as reference to build your kernel for specific tests.

**Comment by weishan18** [comment]
Hi, @rli9 
Is it we need to make a rspec test on the kernel_match_kconfig?() in need_kconfig.rb? like we provide a few test cases for this function, to check if it raise error for wrong need_kconfig format?
