### ISSUE TITLE
lkp-tests install hackbench schbench fails

### ISSUE THREAD

**Issue by yu-chen-surf** [intel/lkp-tests#247]
If running "lkp-tests install hackbench.yaml" after schbench is installed, the /lkp/benchmark/schbench will be removed automatically.

steps to reproduce:
1.lkp install schbench.yaml
2.ls /lkp/benchmark
    schbench 
3. lkp install hackbench.yaml
4.ls /lkp/benchmark
    hackbench   (schbench is missing)

**Comment by Yujie-Liu** [comment]
Hi @yu-chen-surf, thanks for reporting this issue. Could you update to the latest lkp-tests code to see if the issue is fixed now?

**Comment by yu-chen-surf** [comment]
Yes, it works for me now, thanks!
