### ISSUE TITLE
Bug: libhugetlbfs-test multiple pagenums

### ISSUE THREAD

**Issue by johnbieren** [intel/lkp-tests#29]
https://github.com/intel/lkp-tests/blob/master/jobs/libhugetlbfs-test.yaml
lists both 32 and 64 for pagenums. 
When that is fed into this (at least on rpm distros):
https://github.com/intel/lkp-tests/blob/master/tests/libhugetlbfs-test#L14
it results in the command including `--add-temp-swap=32 64 --pool-pages-min` which is not proper syntax to hugeadm. Should the test loop on pagenum value or something instead?

**Comment by rli9** [comment]
thanks for the input, we will look into it shortly.

**Comment by zhijianli88** [comment]
Looks we can use https://github.com/intel/lkp-tests/blob/master/tests/libhugetlbfs-test#L14
to setup page number correctly.
```
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-pages-max 2MB:32                   
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-list
      Size  Minimum  Current  Maximum  Default
   2097152       32       32       32        *
1073741824        1        1        1         
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-pages-min 2MB:256                   
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-list
      Size  Minimum  Current  Maximum  Default
   2097152      256      256      256        *
1073741824        1        1        1         
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-pages-min 2MB:512 --add-temp-swap=512 
mkswap: /var/lib/hugetlbfs/swap/temp/swapfile-7161: insecure permissions 0664, 0600 suggested.
Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
no label, UUID=3c7c1726-06e4-4581-9b1a-57076ea5f5b4
hugeadm:WARNING: swapon on /var/lib/hugetlbfs/swap/temp/swapfile-7161 failed: Invalid argument
root@lkp-bdw-ep3b /lkp/benchmarks/libhugetlbfs-test# obj/hugeadm --pool-list
      Size  Minimum  Current  Maximum  Default
   2097152      512      512      512        *
1073741824        1        1        1     
```

this step is a preparation for later test(make check)
according to our test result, it looks the tests need at least 32 * 2M pages

**Comment by zhijianli88** [comment]
IIRC, this test(make check) cannot test  specified pagenums, but our job.yaml describe pagenum which might cause a bit confusion for users.

**Comment by johnbieren** [comment]
Right, I wasn't questioning the number of pages, it just seems that as written, it passes `--add-temp-swap=32 64 `, and -add-temp-swap expects a singular value, not a space separated list of them. I expected that running install then run on the test would work, but it trips up on the syntax passed to hugeadm

**Comment by zhijianli88** [comment]
Not exactly, we need  split job first and then run job
```
$ lkp split-job jobs/libhugetlbfs-test.yaml
$ lkp run xxxx.yaml
```
split will split a large job to multiple atomic jobs
so if run origin job directly(jobs/libhugetlbfs-test.yaml), it would cause the issue as you said.

**Comment by johnbieren** [comment]
Ah, I understand now. I didn't know about the split-job functionality. It works as expected for me now, thanks!
