### ISSUE TITLE
Can I use this in ARM64 for Android?

### ISSUE THREAD

**Issue by butterl** [intel/lkp-tests#3]
Hi
From the Read me seems ARM64 is not said support, is there a possible  to run it on ARM64 android phone ?
BRs,
Chao

**Comment by rli9** [comment]
Currently it doesn't support OS like Android. The running environment like packages on Android are quite different than usual Linux distribution, that we haven't done investigation yet to know the gaps and effort.

**Comment by butterl** [comment]
Hi rli9, 
Thanks for your reply !
So the main issue is the cross compile or maybe some ARM/AARch64 support patches are also needed in the lkp-tests suits?

Thanks!

**Comment by rli9** [comment]
we use "lkp run" tool to execute tests, which involves the usage like apt-get/yum (can refer to distro/installer). So to make android part work, it is mostly to add support for how we pack the test suites, install required dependencies.
