### ISSUE TITLE
perf: Error: unknown switch `c'

### ISSUE THREAD

**Issue by hrw** [intel/lkp-tests#35]
lkp may need changes to adapt to perf from Linux 5.1:

```
root@33c9bf576e93:~/lkp-tests# lkp run  ./hackbench-socket-threads-50%.yaml
2019-03-28 10:46:37 +0000 WARN -- skip non-executable /root/lkp-tests/stats/build-ceph
/root/lkp-tests/monitors/vmstat: 5: /root/lkp-tests/monitors/vmstat: vmstat: not found
/root/lkp-tests/monitors/heartbeat: 5: /root/lkp-tests/monitors/heartbeat: vmstat: not found
/root/lkp-tests/monitors/heartbeat: 23: exec: vmstat: not found
/root/lkp-tests/monitors/vmstat: 23: exec: vmstat: not found
/root/lkp-tests/monitors/mpstat: 27: /root/lkp-tests/monitors/mpstat: /lkp/benchmarks/sysstat/usr/local/bin/mpstat: not found                                                                  
dmesg: read kernel buffer failed: Operation not permitted
dmesg: read kernel buffer failed: Operation not permitted
/root/lkp-tests/monitors/perf-stat: 89: /root/lkp-tests/monitors/perf-stat: cannot create /proc/sys/kernel/nmi_watchdog: Read-only file system                                                 
  Error: unknown switch `c'

 Usage: perf stat [<options>] [<command>]
```

```
root@33c9bf576e93:~/lkp-tests# /lkp/benchmarks/perf/perf --version
perf version 5.1.rc2.g14c741
```

**Comment by zhijianli88** [comment]
Thanks for your reporting.

Looks there are some many errors/warnings on you environment
what's your distribution.

> lkp may need changes to adapt to perf from Linux 5.1:
> 
> ```
> root@33c9bf576e93:~/lkp-tests# lkp run  ./hackbench-socket-threads-50%.yaml
> 2019-03-28 10:46:37 +0000 WARN -- skip non-executable /root/lkp-tests/stats/build-ceph
> /root/lkp-tests/monitors/vmstat: 5: /root/lkp-tests/monitors/vmstat: vmstat: not found

i will fix this soon

> /root/lkp-tests/monitors/heartbeat: 5: /root/lkp-tests/monitors/heartbeat: vmstat: not found
> /root/lkp-tests/monitors/heartbeat: 23: exec: vmstat: not found
> /root/lkp-tests/monitors/vmstat: 23: exec: vmstat: not found
> /root/lkp-tests/monitors/mpstat: 27: /root/lkp-tests/monitors/mpstat: /lkp/benchmarks/sysstat/usr/local/bin/mpstat: not found           

have  you installed   ./hackbench-socket-threads-50%.yaml successfully ?
mpstat should be installed when you install this job i think
                                                 

> dmesg: read kernel buffer failed: Operation not permitted
> dmesg: read kernel buffer failed: Operation not permitted
> /root/lkp-tests/monitors/perf-stat: 89: /root/lkp-tests/monitors/perf-stat: cannot create /proc/sys/kernel/nmi_watchdog: Read-only file system                                                 
>   Error: unknown switch `c'

i will have a look.

> 
>  Usage: perf stat [<options>] [<command>]
> ```
> ```
> root@33c9bf576e93:~/lkp-tests# /lkp/benchmarks/perf/perf --version
> perf version 5.1.rc2.g14c741
> ```

**Comment by zhijianli88** [comment]
Figure out the FBC
```shell
75998bb263bf48c1c85d78cd2d2f3a97d3747cab is the first bad commit
commit 75998bb263bf48c1c85d78cd2d2f3a97d3747cab
Author: Andi Kleen <ak@linux.intel.com>
Date:   Thu Mar 14 15:50:01 2019 -0700

    perf stat: Fix --no-scale
    
    The -c option to enable multiplex scaling has been useless for quite
    some time because scaling is default.
    
    It's only useful as --no-scale to disable scaling. But the non scaling
    code path has bitrotted and doesn't print anything because perf output
    code relies on value run/ena information.
    
    Also even when we don't want to scale a value it's still useful to show
    its multiplex percentage.
    
    This patch:
      - Fixes help and documentation to show --no-scale instead of -c
      - Removes -c, only keeps the long option because -c doesn't support negatives.
      - Enables running/enabled even with --no-scale
      - And fixes some other problems in the no-scale output.
    
    Before:
    
      $ perf stat --no-scale -e cycles true
    
       Performance counter stats for 'true':
    
           <not counted>      cycles
    
             0.000984154 seconds time elapsed
    
    After:
    
      $ ./perf stat --no-scale -e cycles true
    
       Performance counter stats for 'true':
    
                 706,070      cycles
    
             0.001219821 seconds time elapsed
    
    Signed-off-by: Andi Kleen <ak@linux.intel.com>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    LPU-Reference: 20190314225002.30108-9-andi@firstfloor.org
    Link: https://lkml.kernel.org/n/tip-xggjvwcdaj2aqy8ib3i4b1g6@git.kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

:040000 040000 91c6465ee19b49aa817ac0969e9328f84b74ffd3 96daf594883c98e46e79870e064e81f9f981a7c4 M	tools
```

**Comment by hrw** [comment]
> Thanks for your reporting.
> 
> Looks there are some many errors/warnings on you environment
> what's your distribution.

I used debian:buster container container as it was just quick check as one of my coworkers had issues with lkp. 

So some issues may be a reason of running in Docker container instead of system installed on bare metal.

> > /root/lkp-tests/monitors/heartbeat: 5: /root/lkp-tests/monitors/heartbeat: vmstat: not found
> > /root/lkp-tests/monitors/heartbeat: 23: exec: vmstat: not found
> > /root/lkp-tests/monitors/vmstat: 23: exec: vmstat: not found
> > /root/lkp-tests/monitors/mpstat: 27: /root/lkp-tests/monitors/mpstat: /lkp/benchmarks/sysstat/usr/local/bin/mpstat: not found
> 
> have you installed ./hackbench-socket-threads-50%.yaml successfully ?
> mpstat should be installed when you install this job i think
 
Once I got rid of turbostat installation ended without errors.
