### ISSUE TITLE
Failure when using output created by "lkp compile lkp-test/tests/phoronix-test-suite.yaml"

### ISSUE THREAD

**Issue by sriiora** [intel/lkp-tests#38]
Steps to reproduce
1. phoronix-test-suite try to connect to the Internet, if use http proxy, please run 'phoronix-test-suite network-setup'

2.  Create an auto execution bash script
```
    $ lkp compile lkp-tests/tests/phoronix-test-suite.yaml > phoronix-test-suite.sh
    $ chmod a+x phoronix-test-suite.sh
    $ mkdri -p result
    $ yes 2 | sudo lkp run -o result/ phoronix-test-suite.sh
```

2. The execution will only run the first test suite, in this case it is "aio-stress-1.1.1"

3. Refer to the attach for the quick hack fix [phoronix-test-suite.zip](https://github.com/intel/lkp-tests/files/3409301/phoronix-test-suite.zip)

4. This type issue exists in most of the tests that use the output by using "lkp compile ..." command. It also has problem with input parameters that not numeric, e.g. 50%, 12.5% and 100%.

**Comment by rli9** [comment]
Thanks @sriiora, lkp compile is lacks maintenance, we will put effort to check it. BTW: whether lkp install/lkp run work as expected in this scenario?

**Comment by sriiora** [comment]
yup, lkp install/lkp run work as expected. The only draw back is the execution time is long vs the batch more.

**Comment by zhijianli88** [comment]
Hey @sriiora , 

Looks we need to document more about 'lkp compare'

when i tried to compile a splited(atomic) job, it worked as expected
```
root@clear-lkp-30040~/jobs # lkp compile phoronix-test-suite-clearlinux-stress-ng-1.2.2-clear-24300-phoronix-x86_64.yaml >a.sh
root@clear-lkp-30040~/jobs # chmod +x a.sh 
root@clear-lkp-30040~/jobs # lkp run -o /wtf a.sh 
phoronix-test-suite try to connect to the Internet, if use http proxy, please run 'phoronix-test-suite network-setup'


New user configuration file written: /etc/phoronix-test-suite.xml


Installing stress-ng-1.2.2 ...
Please make sure phoronix-test-suite can connect to the Internet.




Phoronix Test Suite v8.8.1

    Installed:     pts/stress-ng-1.2.2

PTS_SILENT_MODE=1
spawn phoronix-test-suite default-run stress-ng-1.2.2

    Would you like to save these test results (Y/n): n

Stress-NG 0.07.26:
    pts/stress-ng-1.2.2 [Test: CPU Stress]
    Test 1 of 1
    Estimated Trial Run Count:    3                     
    Estimated Time To Completion: 2 Minutes [09:43 UTC] 
        Started Run 1 @ 09:41:27
        Started Run 2 @ 09:42:02
        Started Run 3 @ 09:42:36

    Test: CPU Stress:
        1393.24
        1385.53
        1409.45

    Average: 1396.07 Bogo Ops/s
    Deviation: 0.87%

stress-ng-1.2.2.seconds: 122.897629556
kill 21874 vmstat --timestamp -n 10 
kill 21864 dmesg --follow --decode 
kill 21880 vmstat --timestamp -n 1 
wait for background processes: 21926 21907 21868 21898 21947 21956 21988 21904 21914 21998 21984 interrupts meminfo uptime proc-vmstat softirqs diskstats sched_debug proc-stat slabinfo mpstat turbostat
curl: (22) The requested URL returned error: 503 Service Unavailable
curl: (22) The requested URL returned error: 503 Service Unavailable
root@clear-lkp-30040~/jobs # ls /wtf/
bdi_dev_mapping  cpuidle       heartbeat      iostat.gz  latency_stats  meminfo.gz  nfsstat          numa-numastat.gz  perf-stat.gz         proc-stat.gz    sched_debug.gz  softirqs.gz  turbostat  vmstat
cpufreq-stats    diskstats.gz  interrupts.gz  kmsg       lock_stat      mpstat      numa-meminfo.gz  numa-vmstat.gz    phoronix-test-suite  proc-vmstat.gz  slabinfo        time-debug   uptime
root@clear-lkp-30040~/jobs # cat /wtf/phoronix-test-suite 
phoronix-test-suite try to connect to the Internet, if use http proxy, please run 'phoronix-test-suite network-setup'


New user configuration file written: /etc/phoronix-test-suite.xml


Installing stress-ng-1.2.2 ...
Please make sure phoronix-test-suite can connect to the Internet.




Phoronix Test Suite v8.8.1

    Installed:     pts/stress-ng-1.2.2

PTS_SILENT_MODE=1
spawn phoronix-test-suite default-run stress-ng-1.2.2

    Would you like to save these test results (Y/n): n

Stress-NG 0.07.26:
    pts/stress-ng-1.2.2 [Test: CPU Stress]
    Test 1 of 1
    Estimated Trial Run Count:    3                     
    Estimated Time To Completion: 2 Minutes [09:43 UTC] 
        Started Run 1 @ 09:41:27
        Started Run 2 @ 09:42:02
        Started Run 3 @ 09:42:36

    Test: CPU Stress:
        1393.24
        1385.53
        1409.45

    Average: 1396.07 Bogo Ops/s
    Deviation: 0.87%

stress-ng-1.2.2.seconds: 122.897629556
```

**Comment by sriiora** [comment]
Question:
1. I git clone https://github.com/intel/lkp-tests.git and I cannot locate phoronix-test-suite-clearlinux-stress-ng-1.2.2-clear-24300-phoronix-x86_64.yaml in lkp-tests/jobs. ???

2. the command " lkp compile xxxx.yaml" need to apply to the atomic level YAML file that split out from the master YAML? Or it can directly use on the master YAML file in lkp-tests/jobs? I use the 2nd method and it always excute the first test suite only.

**Comment by zhijianli88** [comment]
> * I git clone https://github.com/intel/lkp-tests.git and I cannot locate phoronix-test-suite-clearlinux-stress-ng-1.2.2-clear-24300-phoronix-x86_64.yaml in lkp-tests/jobs. ???
No, it's my private atomic yaml, you can split jobs/phoronix-test-suite.yaml to get similar atomic yaml files.

> * the command " lkp compile xxxx.yaml" need to apply to the atomic level YAML file that split out from the master YAML?
That's true

> Or it can directly use on the master YAML file in lkp-tests/jobs? I use the 2nd method and it always excute the first test suite only.
this isn't still supported though lkp doesn't complain
