### ISSUE TITLE
unixbench: libperl5.24 does not exist on ubuntu-18.04

### ISSUE THREAD

**Issue by jallen-amd** [intel/lkp-tests#42]
ubuntu-18.04 repos seem to only contain libperl5.26 and perl-modules-5.26, but unixbench attempts to install 5.24. Is ubuntu 18.04 not a supported distro? If it is supported, it seems that we will need a way to specify to install whichever version of the package is available. Ideally, it would be nice to be able to specify something like "perl-modules >= 5.26", but the current method of installing packages doesn't seem to be equipped to handle that sort of thing.

**Comment by rli9** [comment]
@jallen-amd would you give a try for the latest code base?

**Comment by jallen-amd** [comment]
@rli9: Issue appears to be resolved for the latest code base. Thanks!
