### ISSUE TITLE
Unable to add arugments to a new job file with cyclictest

### ISSUE THREAD

**Issue by ckoppolu** [intel/lkp-tests#44]
The examples for cyclictest under jobs/autotest-part1 do not have examples with parameters passed. While out-of-box tests for cyclictest when executed from autotest-part1(autotest-part1-cyclictest.yaml) work fine. 

Example cyclictest without arugments which works fine is autotest-cyclictest.yaml:
suite: autotest
testcase: autotest
category: functional

autotest:
  test:
  - cyclictest

I see in the test results that the cyclictest ran with args: -t 10 -l 100000
I want to run cyclictest with parameters: -S -p 99 -d 0 -m -D 10s -h 400 -q

What are the steps to follow to be able to execute a test with the above parameters.

**Comment by q384566678** [comment]
The default command is written in the relevant test file.
```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/tests/cyclictest # cat cyclictest.py
import os
from autotest.client import test
from autotest.client.shared import utils


class cyclictest(test.test):
    version = 2
    preserve_srcdir = True

    # git://git.kernel.org/pub/scm/linux/kernel/git/tglx/rt-tests.git
    def initialize(self):
        self.job.require_gcc()

    def setup(self):
        os.chdir(self.srcdir)
        utils.make()

    def execute(self, args='-t 10 -l 100000'):
        utils.system(self.srcdir + '/cyclictest ' + args)

```
If you want to change the command, you can modify the related files.
```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/tests/cyclictest # git diff
diff --git a/cyclictest/cyclictest.py b/cyclictest/cyclictest.py
index ad5b69fc..0109ddce 100644
--- a/cyclictest/cyclictest.py
+++ b/cyclictest/cyclictest.py
@@ -15,5 +15,5 @@ class cyclictest(test.test):
         os.chdir(self.srcdir)
         utils.make()

-    def execute(self, args='-t 10 -l 100000'):
+    def execute(self, args='-S -p 99 -d 0 -m -D 10s -h 400 -q'):
         utils.system(self.srcdir + '/cyclictest ' + args)
```
Verify that the modified command takes effect.
```
root@clear-lkp-30040/lkp/result/autotest/cyclictest/clear-lkp/clear-linux-os/x86_64-rhel-7.6/gcc-7/5.1.12-357.kvm/7 # cat results/default/debug/client.DEBUG
...
07/29 06:33:37 DEBUG|     utils:0115| Running 'which gcc'
07/29 06:33:37 DEBUG|     utils:0152| [stdout] /usr/bin/gcc
07/29 06:33:37 DEBUG|     utils:0115| Running '/lkp/benchmarks/autotest/client/tmp/cyclictest/src/cyclictest -S -p 99 -d 0 -m -D 10s -h 400 -q'
07/29 06:33:37 ERROR|     utils:0152| [stderr] /lkp/benchmarks/autotest/client/tmp/cyclictest/src/cyclictest: invalid option -- 'S'
...

```

**Comment by q384566678** [comment]
I tried to pass args directly through the command, but it didn't succeed, maybe the method I used was wrong. The current method above is a viable method I have found. As for the revision through the order, I am still trying.
```
root@clear-lkp-30040/lkp/benchmarks/autotest # python2.7 client/autotest-local --args='-S -p 99 -d 0 -m -D 10s -h 400 -q' run cyclictest
08:40:26 INFO | Writing results to /lkp/benchmarks/autotest/client/results/default
08:40:26 ERROR| Could not determine initlevel, assuming 2
08:40:26 INFO | Could not symlink init scripts (lack of permissions)
08:40:26 INFO | START   ----    ----    timestamp=1564389626    localtime=Jul 29 08:40:26
08:40:26 INFO |         START   cyclictest      cyclictest      timestamp=1564389626    localtime=Jul 29 08:40:26
08:40:26 WARNI| System python is too old, crash handling disabled
08:42:07 INFO | System log file not found (looked for ['/var/log/messages', '/var/log/syslog'])
08:42:07 INFO |                 GOOD    cyclictest      cyclictest      timestamp=1564389727    localtime=Jul 29 08:42:07       completed successfully
08:42:08 INFO |         END GOOD        cyclictest      cyclictest      timestamp=1564389728    localtime=Jul 29 08:42:08
08:42:08 INFO | END GOOD        ----    ----    timestamp=1564389728    localtime=Jul 29 08:42:08
```


```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/results/default # cat debug/client.DEBUG
....
07/29 08:40:26 DEBUG|     utils:0115| Running 'which gcc'
07/29 08:40:26 DEBUG|     utils:0152| [stdout] /usr/bin/gcc
07/29 08:40:26 DEBUG|     utils:0115| Running '/lkp/benchmarks/autotest/client/tmp/cyclictest/src/cyclictest -t 10 -l 100000'
07/29 08:40:26 DEBUG|     utils:0152| [stdout] 0.05 0.11 0.09 3/129 3061
```

**Comment by ckoppolu** [comment]
I see that the cyclictest version checked out from git://git.kernel.org/pub/scm/linux/kernel/git/tglx/rt-tests.git(as mentioned in the script) seems to be 0.15 where the latest version is 1.00. There aren't all the options that we use are available in the older version.

**Comment by q384566678** [comment]
Since the option is not supported, if you want to use other args, you can only modify the relevant files according to the above method.
```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/tests/cyclictest # git diff
diff --git a/cyclictest/cyclictest.py b/cyclictest/cyclictest.py
index ad5b69fc..0109ddce 100644
--- a/cyclictest/cyclictest.py
+++ b/cyclictest/cyclictest.py
@@ -15,5 +15,5 @@ class cyclictest(test.test):
         os.chdir(self.srcdir)
         utils.make()

-    def execute(self, args='-t 10 -l 100000'):
+    def execute(self, args='-S -p 99 -d 0 -m -D 10s -h 400 -q'):
         utils.system(self.srcdir + '/cyclictest ' + args)
```

**Comment by ckoppolu** [comment]
Is there a configuration file that I can modify to pull the rt-tests from a different repo that uses latest version of cyclictest? If so, where is the file to modify?

**Comment by q384566678** [comment]
You can use the library you want to use by modifying the address of the library in the following file.
```
➜  lkp-tests git:(master) ✗ cat pack/autotest 
#!/bin/bash

download()
{
        git_clone_update https://github.com/autotest/autotest.git --recursive
}

install()
{
        cp -af $source_dir /lkp/benchmarks/
}
```

**Comment by ckoppolu** [comment]
Hello Zhou,

Since the version of cyclictest is old in the repo https://github.com/autotest/autotest.git. Can we request the maintainers to update the repo to use the latest version of cyclictest? Or to make things easier, can we make a pull request?

Regards,
Chanakya

**Comment by q384566678** [comment]
for this specific usage (not general applicable or a lkp issue), I suggest you make a pull request in the autotest community.

**Comment by seanvk** [comment]
It's unfortunate that we have this dependency chain of lkp-tests->autotest->out-of-date-tests.  Frequently these tests do have bugs which can result in inaccurate results.  Hopefully, we can get that updated.

**Comment by seanvk** [comment]
If you go here:  https://github.com/autotest/autotest-client-tests 
You will see a lot of these tests are like 5 years old or more.  That's independent of this issue but something I think lkp should consider further investigating in general.

**Comment by ckoppolu** [comment]
Hello Zhou,

After speculation and researching autotest, we have decided to add "cyclictest" as a new test to the lkp tests. I need help in writing the relevant files as the documentation is not so clear. Can you please provide me a list of configuration scripts and relevant files to be able to cyclictest as a new test?

**Comment by ckoppolu** [comment]
Added rt-tests.yaml under jobs: cat jobs/rt-tests.yaml 
suite: rt-test
testcase: rt-test
category: benchmark

rt-tests:
  test:
  - cyclictest


And rt-tests under pack: cat pack/rt-tests 
#!/bin/bash

download()
{
	git_clone_update https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git autotest --recursive
}

install()
{
	cp -af $source_dir /lkp/benchmarks/
}


Here is the error message I am geting: 
sudo lkp run ./rt-tests-defaults.yaml 
kill 11562 vmstat --timestamp -n 10 
kill 11549 dmesg --follow --decode 
kill 11567 vmstat --timestamp -n 1 
wait for background processes: 11648 11555 11708 11663 11627 11614 11723 11598 11589 11604 11699 softirqs uptime sched_debug diskstats interrupts slabinfo mpstat proc-stat proc-vmstat meminfo turbostat
Last record seems incomplete. Truncated /lkp/result/rt-test/defaults/ckoppolu-rtse/ubuntu/x86_64-rhel-7.6/gcc-7/4.15.0-62-generic/3/slabinfo.json
Traceback (most recent call last):
	5: from /home/ckoppolu/projects/lkp-tests/bin/run-local:159:in `<main>'
	4: from /home/ckoppolu/projects/lkp-tests/lib/result_root.rb:374:in `convert_mrt'
	3: from /home/ckoppolu/projects/lkp-tests/lib/result_root.rb:339:in `convert_one_mresult_root'
	2: from /home/ckoppolu/projects/lkp-tests/lib/nresult_root.rb:316:in `new_node'
	1: from /home/ckoppolu/projects/lkp-tests/lib/nresult_root.rb:312:in `axes_to_table'
/home/ckoppolu/projects/lkp-tests/lib/nresult_root.rb:302:in `testcase_to_table': Unknow testcase: rt-test (RuntimeError)

**Comment by q384566678** [comment]
below is an example:
```
➜  lkp-tests git:(master) ✗ find . -name "autotest"
./include/autotest
./stats/autotest
./pack/autotest
./tests/autotest
./distro/depends/autotest
```
So if you want to add a test with the name cyclictest, you need to add the following files:
* /include/cyclictest
  If the test requires a special kernel configuration, it needs to be written in this file. If it doesn't need it, you don't need to add this file.
* /stats/cyclictest
  Format the result and generate the corresponding cyclictest.json file in rt.
* /pack/cyclictest
  Download, compile, and install the test set.
* /tests/cyclictest
  A script that tests cyclictest.
* /distro/depends/cyclictest
  The dependency package for the test set runtime.

The above is a rough explanation, hope this can help you. 
You can also refer to some specific examples.

**Comment by rli9** [comment]
Closed due to no update for 1 month.
