### ISSUE TITLE
PACKERDRILL:Compilation Error

### ISSUE THREAD

**Issue by skarana1** [intel/lkp-tests#45]
root@SSP-CLXAEP-CDI205/home/labuser/drill/lkp-tests # lkp install ./packetdrill-defaults.yaml
Use: /home/labuser/drill/lkp-tests/distro/installer/clear install bc os-core os-core-update sysadmin-basic c-basic dev-utils dev-utils-dev git linux-tools network-basic openssl os-core-update os-testsuite-0day patch perl-extras ruby-basic
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 1 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
Using rake 12.3.3
Using concurrent-ruby 1.1.5
...........................
.
.
.............
gcc -g -Wall -Werror   -c -o run_packet.o run_packet.c
run_packet.c: In function ‘find_tcp_timestamp’:
run_packet.c:408:13: error: taking address of packed member of ‘struct tcp_option’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  408 |     (void *)&(option->data.time_stamp.val);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_packet.c:410:13: error: taking address of packed member of ‘struct tcp_option’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  410 |     (void *)&(option->data.time_stamp.ecr);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: run_packet.o] Error 1
Making packetdrill-LKP failed
root@SSP-CLXAEP-CDI205/home/labuser/drill/lkp-tests # uname -a
Linux SSP-CLXAEP-CDI205 5.1.12-785.native #1 SMP Wed Jun 19 07:09:10 UTC 2019 x86_64 GNU/Linux
Workaround :-
It seems like there is an incompatibility between packetdrill test suite and gcc9 compiler – compiler complains about an alignment of a pointer in packed struct. the alignment of the pointer value should not be related to the alignment of the pointer variable itself. 
For now, commenting out the werror flag (In the path ::/tmp/build-packetdrill/packetdrill/gtests/net/packetdrill/Makefile.common) and able to build packetdrill test packages successfully without errors.

**Comment by yangx-jy** [comment]
Hi @skarana1 

gcc-9 introduces and enables address-of-packed-member option by default so gcc-9 with -Werror
treats taking address of packed member as a error. 

commit f372040c7cf9 has fixed the issue by disabing address-of-packed-member option as upstream kernel does.

Could you download the lastest lkp-tests code and then check if the issue is gone by 'lkp install ./packetdrill-defaults.yaml".

Best Regards,
Xiao Yang

**Comment by skarana1** [comment]
Hi Yang,
Thanks for the patch.
Can you please provide the patch.

**Comment by yangx-jy** [comment]
Hi @skarana1 

You can see the patch in lkp-tests code, as below:
[root@Fedora-30-workstation lkp-tests]# ll pack/packetdrill.patch 
-rw-r--r--. 1 root root 1677 Aug 10 21:01 pack/packetdrill.patch

This patch just disables address-of-packed-member when the option is supported, and does nothing when the option isn't supported.

Best Regards,
Xiao Yang

**Comment by skarana1** [comment]
Thank you so much Xiao.
I'm hitting another error/fail.Please refer below.
Running ./gtests/net/packetdrill/tests/bsd/fast_retransmit/fr-4pkt-sack-bsd.pkt ...
2019-08-13 01:51:00 ./gtests/net/packetdrill/packetdrill --tolerance_usecs=40000 ./gtests/net/packetdrill/tests/bsd/fast_retransmit/fr-4pkt-sack-bsd.pkt
./gtests/net/packetdrill/tests/bsd/fast_retransmit/fr-4pkt-sack-bsd.pkt:25: error handling packet: live packet payload: expected 1000 bytes vs actual 2000 bytes
./gtests/net/packetdrill/tests/bsd/fast_retransmit/fr-4pkt-sack-bsd.pkt failed
Can you please help me out in this?

**Comment by skarana1** [comment]
Hi, Yang,
With the given patch,lkp install ./packetdrill-defaults.yaml" is working without any issues.
