### ISSUE TITLE
PIGLIT:Compilation error

### ISSUE THREAD

**Issue by skarana1** [intel/lkp-tests#47]
root@hyd-clx-coffeelake/home/testrunner/lkp_packet/lkp-tests # lkp install ./piglit-all-igt-all.yaml
Use: /home/testrunner/lkp_packet/lkp-tests/distro/installer/clear install bc os-core os-core-update sysadmin-basic c-basic dev-utils dev-utils-dev git linux-tools network-basic openssl os-core-update os-testsuite-0day patch perl-extras ruby-basic
Error: Curl - Communicating with server timed out
Error: Failed to connect to update server: https://cdn.download.clearlinux.org/update
Error: Failed updater initialization. Exiting now
Loading required manifests...
Warning: Bundle "ruby-basic" is already installed, skipping it...
1 bundle was already installed
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 1 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
Using rake 12.3.3
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
..............
..................
.............
make -C /home/testrunner/lkp_packet/lkp-tests/bin/event
Use: /home/testrunner/lkp_packet/lkp-tests/distro/installer/clear install c-basic desktop-apps openssl os-core-dev os-core-update os-testsuite-0day sysadmin-basic
Making makepkg benchmark for clear
makepkg is already installed into /lkp/benchmarks/makepkg, skip this packing
Installing makepkg-LKP
Just make /lkp/benchmarks/makepkg-x86_64.cgz
Use: /home/testrunner/lkp_packet/lkp-tests/distro/installer/clear install desktop dev-utils-dev libva-utils os-core-dev python-extras qt-basic-dev xfce4-desktop c-basic c-extras-gcc7 cpp-7 dev-utils dev-utils-dev libgcc1 libgcc-7-dev libmpfr6 libva-utils os-clr-on-clr-dev os-core os-core-dev python2-basic python-extras qt-basic-dev
Loading required manifests...
Warning: Bundle "cpp-7" is invalid, skipping it...
Failed to install 1 of 1 bundles
Loading required manifests...
Warning: Bundle "libgcc1" is invalid, skipping it...
Failed to install 1 of 1 bundles
Loading required manifests...
Warning: Bundle "libgcc-7-dev" is invalid, skipping it...
Failed to install 1 of 1 bundles
Loading required manifests...
Warning: Bundle "libmpfr6" is invalid, skipping it...
Failed to install 1 of 1 bundles
Making piglit benchmark for clear
timeout 60m git remote update origin
Fetching origin
timeout 60m git checkout -q origin/master
timeout 60m git remote update origin
Fetching origin
timeout 60m git checkout -q origin/master
timeout 60m git remote update origin
Fetching origin
timeout 60m git checkout -q origin/master
/home/testrunner/lkp_packet/lkp-tests/pack/piglit: line 27: [: : integer expression expected
[  1%] Built target cmocka
[  2%] Built target threads_bundled
[  3%] Building C object src/waffle/CMakeFiles/waffle-1.dir/wayland/wayland_display.c.o
In file included from /tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:32:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_wrapper.h:99:32: error: conflicting types for ‘wfl_wl_display_roundtrip’
   99 | #define wl_display_roundtrip (*wfl_wl_display_roundtrip)
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_wrapper.h:61:3: note: previous declaration of ‘wfl_wl_display_roundtrip’ was here
   61 | (*wfl_wl_display_roundtrip)(struct wl_display *display);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c: In function ‘registry_listener_global’:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:72:31: error: implicit declaration of function ‘wl_registry_bind’ [-Werror=implicit-function-declaration]
   72 |         self->wl_compositor = wl_registry_bind(self->wl_registry, name,
      |                               ^~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:72:29: error: assignment to ‘struct wl_compositor *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   72 |         self->wl_compositor = wl_registry_bind(self->wl_registry, name,
      |                             ^
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:76:24: error: assignment to ‘struct wl_shell *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   76 |         self->wl_shell = wl_registry_bind(self->wl_registry, name,
      |                        ^
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c: At top level:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:88:21: error: variable ‘registry_listener’ has initializer but incomplete type
   88 | static const struct wl_registry_listener registry_listener = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:89:6: error: ‘const struct wl_registry_listener’ has no member named ‘global’
   89 |     .global = registry_listener_global,
      |      ^~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:89:15: warning: excess elements in struct initializer
   89 |     .global = registry_listener_global,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:89:15: note: (near initialization for ‘registry_listener’)
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:90:6: error: ‘const struct wl_registry_listener’ has no member named ‘global_remove’
   90 |     .global_remove = registry_listener_global_remove
      |      ^~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:90:22: warning: excess elements in struct initializer
   90 |     .global_remove = registry_listener_global_remove
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:90:22: note: (near initialization for ‘registry_listener’)
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c: In function ‘wayland_display_connect’:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:111:25: error: implicit declaration of function ‘wl_display_get_registry’; did you mean ‘wl_display_get_global’? [-Werror=implicit-function-declaration]
  111 |     self->wl_registry = wl_display_get_registry(self->wl_display);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
      |                         wl_display_get_global
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:111:23: error: assignment to ‘struct wl_registry *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  111 |     self->wl_registry = wl_display_get_registry(self->wl_display);
      |                       ^
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:117:13: error: implicit declaration of function ‘wl_registry_add_listener’; did you mean ‘wl_keyboard_add_listener’? [-Werror=implicit-function-declaration]
  117 |     error = wl_registry_add_listener(self->wl_registry,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
      |             wl_keyboard_add_listener
In file included from /tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:32:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c: In function ‘wayland_display_sync’:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_wrapper.h:99:31: error: void value not ignored as it ought to be
   99 | #define wl_display_roundtrip (*wfl_wl_display_roundtrip)
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:184:9: note: in expansion of macro ‘wl_display_roundtrip’
  184 |     if (wl_display_roundtrip(dpy->wl_display) == -1) {
      |         ^~~~~~~~~~~~~~~~~~~~
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c: At top level:
/tmp/build-piglit/waffle/src/waffle/wayland/wayland_display.c:88:42: error: storage size of ‘registry_listener’ isn’t known
   88 | static const struct wl_registry_listener registry_listener = {
      |                                          ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [src/waffle/CMakeFiles/waffle-1.dir/build.make:492: src/waffle/CMakeFiles/waffle-1.dir/wayland/wayland_display.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:592: src/waffle/CMakeFiles/waffle-1.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Making piglit-LKP failed
root@hyd-clx-coffeelake/home/testrunner/lkp_packet/lkp-tests # uname -a
Linux hyd-clx-coffeelake 4.19.1-656.native #1 SMP Tue Nov 13 16:11:01 UTC 2018 x86_64 GNU/Linux

**Comment by q384566678** [comment]
Hi @skarana1, can you delete the files in /tmp/build-piglit and then re-run this command with the latest code?
Please let me know if there are any more problems.
