### ISSUE TITLE
bsdtar is not installable in recent Ubuntu releases

### ISSUE THREAD

**Issue by tyhicks** [intel/lkp-tests#50]
The `bsdtar` binary package is installed, using apt, when running `lkp install` on Ubuntu. This fails since Ubuntu 19.10 as the `bsdtar` binary package no longer exists. The `bsdtar` binary can be found in the `libarchive-tools` binary package in most, but not all, currently supported Ubuntu releases. For `lkp install` to work across all currently supported Ubuntu releases, we need `bsdtar` to be installed on some Ubuntu releases and `libarchive-tools` to be installed on others. Is there a way to specify that in the distro adaptation files?

Here's the breakdown of `bsdtar` to `libarchive-tools` across all currently supported Ubuntu releases:

Ubuntu Release | bsdtar | libarchive-tools
------------|----------|-----------------
Ubuntu Focal | no | yes
Ubuntu 19.10 (Eoan) | no | yes
Ubuntu 19.04 (Disco) | yes[1] | yes
Ubuntu 18.04 LTS (Bionic) | yes[1] | yes
Ubuntu 16.04 LTS (Xenial) | yes | no

[1] `bsdtar` exists as a transitional binary package that depends on `libarchive-tools` so installing `bsdtar` will cause `libarchive-tools` to also be installed

I think the same problem exists in Debian but I haven't tested this. According to the [bsdtar page on packages.debian.org](https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=bsdtar), it looks to me as if `bsdtar` cannot be installed on Debian unstable so the next `bullseye` release will not have an installable `bsdtar` binary package.

**Comment by tyhicks** [comment]
Doing something simple like this results in `lkp install` failing on Ubuntu 16.04 LTS (Xenial) where `libarchive-tools` does not exist:

```
diff --git a/distro/adaptation/ubuntu b/distro/adaptation/ubuntu
index d8416caf2de7..881b20110be2 100644
--- a/distro/adaptation/ubuntu
+++ b/distro/adaptation/ubuntu
@@ -1,3 +1,4 @@
+bsdtar: libarchive-tools
 libtool-bin:
 linux-perf: linux-tools-generic
 linux-tools: linux-tools-generic
```

Is there a more fine-grained syntax available for the adaptation files that allow `bsdtar` to be installed on some releases and `libarchive-tools` on others?

**Comment by tyhicks** [comment]
`lkp install` does fail on Debian Sid in the same manner as Ubuntu 19.10 and newer:
```
$ sudo lkp install
Use: /home/tyhicks/lkp-tests/distro/installer/debian install bc gawk gzip kmod time automake bison bsdtar build-essential bzip2 ca-certificates cpio fakeroot flex gcc git libc6-dev libc6-dev:i386 libipc-run-perl libklibc-dev libssl-dev libtool linux-libc-dev linux-libc-dev:i386 linux-perf make openssl patch rsync ruby ruby-dev wget
Hit:1 http://cdn-fastly.deb.debian.org/debian sid InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian sid/main i386 Packages [8138 kB]
Fetched 8138 kB in 3s (2372 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
Package bsdtar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libarchive-tools:i386 libarchive-tools

E: Package 'bsdtar' has no installation candidate
Cannot install some packages in /home/tyhicks/lkp-tests/distro/depends/lkp
```

**Comment by tyhicks** [comment]
Using apt's regex support to install `bsdtar|libarchive-tools` is probably the best path forward. It both packages when they both exist and only select the one that exists when the other isn't available.

**Comment by ckujau** [comment]
Hm, why is this closed? `lkp install ` is still failing because `bsdtar` is referenced in `distro/depends/lkp-dev`. Was this file forgotten or is this intentional?

**Comment by rli9** [comment]
@ckujau we will further check this, reopen now.

**Comment by xiahui9527** [comment]
@ckujau please try the latest lkp-tests for debian/unstable. The commit "distro/adaptation: add debian-bullseye_sid" has been merged to fix lkp install issue on debian/unstable. 
Feel free to let us know if there still has issue on debian/unstable. Thanks.

**Comment by ckujau** [comment]
Yup, now all dependencies could be resolved and `lkp install` completes w/o error. Thanks for fixing this so quickly!

Another thing I noticed: Debian systems sometimes have [dash](http://gondor.apana.org.au/~herbert/dash/) as `/bin/sh` so many other scripts will error out because of this, but that's material for another bug report :)

**Comment by xiahui9527** [comment]
@ckujau , thanks for the response. This issue will be closed since it already be fixed per your feedback. Please file new issue for other problems. Thanks.
