### ISSUE TITLE
lkp ncompare using source code

### ISSUE THREAD

**Issue by bincykp** [intel/lkp-tests#55]

**Comment by bincykp** [comment]
Hi,

I am new to lkp test suite.I have installed it and found useful in comparing different kernel versions.

.


Attached is the lkp compare test result.



lkp ncompare -s commit="3.10.0-1062.9.1.el7.x86_64" -o commit="3.18.0-rc5" -a
======================= ==================================================================


The lin
15.0-29vs65.txt](https://github.com/intel/lkp-tests/files/4197492/4.15.0-29vs65.txt)
I ran 'lkp ncompare' multiple times and not observed any pointers to code.Please suggest

**Comment by bincykp** [comment]
linux source file in /c/repo/linux.
lkp ncompare should point to which git commit id caused the performance delay.
I ran 'lkp ncompare' multiple times and not observed any pointers to code.Please suggest

**Comment by bincykp** [comment]
Hi,
Can somebody help me to understand it better?

**Comment by xilabao** [comment]
`lkp ncompare` reads the kernel version or commit from result path. e.g. "/lkp/result/will-it-scale/process-100%-brk1/shao2-debian/debian/x86_64-rhel-7.6/gcc-7/4.19.0-4-amd64/0": "4.19.0-4-amd64" is the tested kernel which from `uname -r`. so if you want to test the commit, you can build the kernel with particular name to relate to the commit.

**Comment by bincykp** [comment]
> `lkp ncompare` reads the kernel version or commit from result path. e.g. "/lkp/result/will-it-scale/process-100%-brk1/shao2-debian/debian/x86_64-rhel-7.6/gcc-7/4.19.0-4-amd64/0": "4.19.0-4-amd64" is the tested kernel which from `uname -r`. so if you want to test the commit, you can build the kernel with particular name to relate to the commit.

Thanks ...I will try this
