### ISSUE TITLE
ERROR:  While executing gem ... (NameError) uninitialized constant Gem::RDoc

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#66]
Hi
I am running lkp on FU540 (linux kernel 5.4.3), when I run lkp split-job jobs/aim9.yaml got following error.
traceback (most recent call last):
	11: from /home/root/lkp-tests/sbin/split-job:5:in `<main>'
	10: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /home/root/lkp-tests/lib/job.rb:6:in `<top (required)>'
	 7: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /home/root/lkp-tests/lib/common.rb:9:in `<top (required)>'
	 4: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /home/root/lkp-tests/lib/array_ext.rb:3:in `<top (required)>'
	 1: from /usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.6.5/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/core_ext/enumerable (LoadError)

I tried to resolve this using gem install activesupport then I got error as,

ERROR:  While executing gem ... (NameError)
uninitialized constant Gem::RDoc

Also tried to install rdoc using, gem install rdoc but did not work.

1. How to fix this? 
2. Which ruby version lkp require?

Thanks

**Comment by MaXinjian** [comment]
--> Which ruby version lkp require?
Sorry, but now we only support ruby2.3. Please try again with ruby2.3
$ grep RubyVersion lkp-tests/.rubocop.yml
  TargetRubyVersion: 2.3

**Comment by JillJenny** [comment]
I got an error in ：lkp split-job lkp-tests/jobs/hackbench.yaml
my env: CentOS release 6.3 (Final)
ruby:2.3  how to resolve this problem,can you help me  @MaXinjian 
/root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/core_ext/enumerable (LoadError)
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bae/lkp/lkp-tests/lib/array_ext.rb:3:in `<top (required)>'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bae/lkp/lkp-tests/lib/common.rb:9:in `<top (required)>'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bae/lkp/lkp-tests/lib/job.rb:6:in `<top (required)>'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bae/lkp/lkp-tests/sbin/split-job:5:in `<main>'

**Comment by xiahui9527** [comment]
seems the installation is not complete and some file missing.
@JillJenny, could you please follow the steps at https://github.com/intel/lkp-tests/blob/master/README.md. use "sudo" to avoid permission denied issue.

help to share the log if there still have problem. Thanks.
