### ISSUE TITLE
Alternative of fakeroot

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#69]
Is there any alternative of fakeroot? Can I use pseudo instead of fakeroot for lkp?

**Comment by MaXinjian** [comment]
@Ankita-020696  Do you mean use pseudo instead of fakeroot when makepkg?
Or you just don't want to use fakeroot. If this is the situation, we also support use pack to generate a package.

**Comment by Ankita-020696** [comment]
> @Ankita-020696 Do you mean use pseudo instead of fakeroot when makepkg?
> Or you just don't want to use fakeroot. If this is the situation, we also support use pack to generate a package.

I want to use pseudo instaed of fakeroot.

**Comment by MaXinjian** [comment]
> > @Ankita-020696 Do you mean use pseudo instead of fakeroot when makepkg?
> > Or you just don't want to use fakeroot. If this is the situation, we also support use pack to generate a package.
> 
> I want to use pseudo instaed of fakeroot.
Sorry, now we don't support pseudo. Maybe in the future.

**Comment by Ankita-020696** [comment]
> > > @Ankita-020696 Do you mean use pseudo instead of fakeroot when makepkg?
> > > Or you just don't want to use fakeroot. If this is the situation, we also support use pack to generate a package.
> > 
> > 
> > I want to use pseudo instaed of fakeroot.
> > Sorry, now we don't support pseudo. Maybe in the future.

Thank you for information.
