### ISSUE TITLE
isn't a atomic jobfile, only atomic jobfile is supported 

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#72]
Hello
I am running lkp for **Linux raspberrypi4-64 5.4.51-v8 #1 SMP PREEMPT Mon Jul 20 05:13:46 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux**. After lkp split-job & lkp install, when I run a job  using lkp run **./aim9-add_double-300s.yaml** get following error, 
**2020-07-21 08:51:27 +0000 ERROR -- Looks ./aim9-add_double-300s.yaml isn't a atomic jobfile, only atomic jobfile is supported
2020-07-21 08:51:27 +0000 ERROR -- Please run 'lkp split-job ./aim9-add_double-300s.yaml' first**

How do I fix this?

Thanks

**Comment by xiahui9527** [comment]
Can't reproduce the "isn't a atomic jobfile" problem. This test case works fine on my side.
could you please share your aim9-add_double-300s.yaml after split?  It supposed to include only one test "test: add_double". Thanks.
