### ISSUE TITLE
split job error

### ISSUE THREAD

**Issue by JillJenny** [intel/lkp-tests#75]
I got an error in ：lkp split-job lkp-tests/jobs/hackbench.yaml
my env: CentOS release 6.3 (Final)
ruby:2.3 how to resolve this problem,can you help me @MaXinjian

/root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require': cannot load such file -- active_support/core_ext/enumerable (LoadError) from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
from /home/bae/lkp/lkp-tests/lib/array_ext.rb:3:in <top (required)>' from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /home/bae/lkp/lkp-tests/lib/common.rb:9:in <top (required)>'
from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
from /home/bae/lkp/lkp-tests/lib/job.rb:6:in <top (required)>' from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require'
from /root/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /home/bae/lkp/lkp-tests/sbin/split-job:5:in

**Comment by JillJenny** [comment]
can anybody help,

**Comment by xiahui9527** [comment]
seems the installation is not complete and some file missing.
@JillJenny, could you please follow the steps at https://github.com/intel/lkp-tests/blob/master/README.md. use "sudo" to avoid permission denied issue.

help to share the log if there still have problem. Thanks.
