### ISSUE TITLE
Time of run 

### ISSUE THREAD

**Issue by pankajjoshi347** [intel/lkp-tests#77]
Hi,
I am running LKP on two different arch, x86 and ARM(RPI4 ) but able to see the difference in ti me for each iteration however it is taking approximately same for x86 but there is variation in time for running LKP on Raspberry pi.
What all factors i should consider to know the exact reason of degradations like why it is taking long  ?? Kindly suggest.

Thank you

**Comment by xilabao** [comment]
Hi @embdlover , we didn't try LKP on Raspberry pi, do you know which step is long on your environment? could you attach the logs you tested?

**Comment by rli9** [comment]
Closed due to no update for 1 month.
