### ISSUE TITLE
Run job.yaml failed in Xsever

### ISSUE THREAD

**Issue by cooper-chiou** [intel/lkp-tests#78]
I installed lkp-tests on Ubuntu 18.04 machine, and run jobs.yaml on it to reproduce "https://patchwork.kernel.org/patch/11780373/" patch regression issue.
But I got the following Xserver error, could anyone help to check how to resolve it on jobs.yaml. Thanks,

~/lkp-tests$ sudo lkp run job.yaml
2020-10-07 17:17:26 
for cpu_dir in /sys/devices/system/cpu/cpu[0-9]*
do
	online_file="$cpu_dir"/online
	[ -f "$online_file" ] && [ "$(cat "$online_file")" -eq 0 ] && continue

	file="$cpu_dir"/cpufreq/scaling_governor
	[ -f "$file" ] && echo "performance" > "$file"
done

IPMI BMC is not supported on this machine, skip bmc-watchdog setup!

_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 7 requests (7 known processed) with 0 events remaining.

**Comment by xilabao** [comment]
@cooper-chiou  I found a similar problem at https://unix.stackexchange.com/questions/478742/error-when-trying-to-use-xorg-only-console-users-are-allowed-to-run-the-x-serve, the problem is that you already enabled a X server that xinit can't work anymore, could you run "xhost +" with the normal user, and remove 'xinit' from lkp-tests/tests/phoronix-test-suite?

**Comment by cooper-chiou** [comment]
Thanks @xilabao , it's working to resolve this error by your instruction. appreciated.
