### ISSUE TITLE
NUC device shut down while running "phoronix-test-suite run supertuxkart-1.5.2"

### ISSUE THREAD

**Issue by cooper-chiou** [intel/lkp-tests#79]
I installed Ubuntu 18.04.4 LTS (kernel: v5.4) on Intel NUC8, and installed lkp-tests.

But when I run "phoronix-test-suite run supertuxkart-1.5.2" on NUC8, then system always goes shut down soon. Therefore, I can't fully complete the performance test to validate my upstream patch (https://patchwork.kernel.org/project/intel-gfx/patch/20200916180745.627-1-cooper.chiou@intel.com/)

Please help on this urgent issue. Thanks,

The log is as attached.
[run_log.txt](https://github.com/intel/lkp-tests/files/5487281/run_log.txt)

**Comment by ZhengjunXing** [comment]
I check the attached log, no abnormal find. For this issue, it is better to capture the kernel logs(dmesg, uart logs...)

**Comment by cooper-chiou** [comment]
After used my NUC7i3BNH to replace previous NUC8i7HVK4 (it has AMD dGPU), now there is no any device shut down issue on NUC7, I think it might be due to AMD dGPU issue.
I’ll try to disable AMD dGPU in NUC8 BIOS to check.

**Comment by cooper-chiou** [comment]
Closed this issue since my NUC8 can't enable AMD dGPU well as there is libEGL_mesa.so error when add AMD Vega M GPU firmware, and nomodeset is not able to run lkp-test what cased shutdown issue, therefore I think NUC8 with AMD GPU is not good sample to run lkp-tests per my experiment.
