### ISSUE TITLE
How to compare two kernel release? (one results copied from another machine)

### ISSUE THREAD

**Issue by ethercflow** [intel/lkp-tests#80]
Hi, I'm benching CentOS 7 and CentOS 8 with `lkp-tests` on two machines, both have 3 runs. Then copied CentOS 7's result to CentOS 8's:

```sh
➜  ~ tree -L 2 /lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc
/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc
├── 3.10.0-1127.19.1.el7.x86_64
│   ├── 0
│   ├── 1
│   ├── 2
│   ├── avg.csv
│   ├── avg.json
│   ├── desc.yaml
│   ├── matrix.csv
│   ├── matrix.json
│   ├── stddev.csv
│   └── stddev.json
└── 4.18.0-193.19.1.el8_2.x86_64
    ├── 0
    ├── 1
    ├── 2
    ├── avg.csv
    ├── avg.json
    ├── desc.yaml
    ├── matrix.csv
    ├── matrix.json
    ├── stddev.csv
    └── stddev.json

8 directories, 14 files
```

Then I run:

`lkp ncompare -s commit="3.10.0-1127.19.1.el7.x86_64.x86_64" -o commit="4.18.0-193.19.1.el8_2.x86_64" -a`

but got nothing.

So I want to know is there a way to compare two release? Thanks!

**Comment by xilabao** [comment]
@ethercflow 
not sure which commit was run in local, you can generate the file for the copied commit: /lkp/data/mresult_root/linux_perf/index/DataStore::AxisIndex-commit/$commit, then 'lkp ncompare' works

**Comment by ethercflow** [comment]
Thanks! I'll try it when I get the env back.

**Comment by ethercflow** [comment]
> @ethercflow
> not sure which commit was run in local, you can generate the file for the copied commit: /lkp/data/mresult_root/linux_perf/index/DataStore::AxisIndex-commit/$commit, then 'lkp ncompare' works

Hi @xilabao , thanks for your help!

I tried to **generate the commit file** for 3.10 as follows:

```sh
cd /lkp/data/mresult_root/linux_perf/index/DataStore::AxisIndex-commit/
cp -a 4.18.0-193.el8.x86_64 3.10.0-1127.19.1.el7.x86_64
# change file 3.10.0-1127.19.1.el7.x86_64's data to
commit=3.10.0-1127.19.1.el7.x86_64/compiler=gcc/kconfig=defconfig/message_threads=100%/rootfs=centos/tbox_group=localhost.localdomain/testcase=schbench
``` 

Then run 
```sh
lkp ncompare -s commit="3.10.0-1127.19.1.el7.x86_64" -o commit="4.18.0-193.el8.x86_64" -a
```

This time I can get the compared result, but all the item of `3.10.0-1127.19.1.el7.x86_64` is zero.

![image](https://user-images.githubusercontent.com/38067786/99941489-10d43e00-2da9-11eb-9c87-035424ab802d.png)

And `lkp result schbench` still shows 4.18 only

```sh
➜  DataStore::AxisIndex-commit lkp result schbench
/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/4.18.0-193.el8.x86_64/0/
/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/4.18.0-193.el8.x86_64/1/
/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/4.18.0-193.el8.x86_64/2/
```

Is the way I generate the commit wrong or anything I missed?

**Comment by xilabao** [comment]
@ethercflow 
The empty value in `lkp ncompare` is due to no result root found in /lkp/data/mresult_root/linux_perf/storage/
```
$ ruby -e "require 'digest/sha1'; puts Digest::SHA1.hexdigest 'commit=3.10.0-1127.19.1.el7.x86_64/compiler=gcc/kconfig=defconfig/message_threads=100%/rootfs=centos/tbox_group=localhost.localdomain/testcase=schbench'"
3b17e9442d1b121cfd92af1b37f2f05bf83792c5
$ ln -s /lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/3.10.0-1127.19.1.el7.x86_64 /lkp/data/mresult_root/linux_perf/storage/3b/3b17e9442d1b121cfd92af1b37f2f05bf83792c5
```

> lkp result schbench still shows 4.18 only
It's anther problem, you need to save the result path in /lkp/paths/
```
# file format is like 2020-10-30-root
$ echo "/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/3.10.0-1127.19.1.el7.x86_64/0" >> /lkp/paths/$DATE-$USER
```

**Comment by ethercflow** [comment]
> @ethercflow
> The empty value in `lkp ncompare` is due to no result root found in /lkp/data/mresult_root/linux_perf/storage/
> 
> ```
> $ ruby -e "require 'digest/sha1'; puts Digest::SHA1.hexdigest 'commit=3.10.0-1127.19.1.el7.x86_64/compiler=gcc/kconfig=defconfig/message_threads=100%/rootfs=centos/tbox_group=localhost.localdomain/testcase=schbench'"
> 3b17e9442d1b121cfd92af1b37f2f05bf83792c5
> $ ln -s /lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/3.10.0-1127.19.1.el7.x86_64 /lkp/data/mresult_root/linux_perf/storage/3b/3b17e9442d1b121cfd92af1b37f2f05bf83792c5
> ```
> 
> > lkp result schbench still shows 4.18 only
> 
> It's anther problem, you need to save the result path in /lkp/paths/
> 
> ```
> # file format is like 2020-10-30-root
> $ echo "/lkp/result/schbench/100%/localhost.localdomain/centos/defconfig/gcc/3.10.0-1127.19.1.el7.x86_64/0" >> /lkp/paths/$DATE-$USER
> ```

Thanks a lot!
