### ISSUE TITLE
ERROR: One or more files did not pass the validity check! Install aim9 failed

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#87]
Hi,
I am getting **Install aim9 failed** error with aim9-lkp run.

 aim9::
==> Making package: aim9 1-1 (Mon Dec 28 10:28:48 IST 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading s9110.tar.Z...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   397    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   375  100   375    0     0    207      0  0:00:01  0:00:01 --:--:--     0
100   138  100   138    0     0     60      0  0:00:02  0:00:02 --:--:--    60
100   310  100   310    0     0     87      0  0:00:03  0:00:03 --:--:--   522
100  168k  100  168k    0     0  20738      0  0:00:08  0:00:08 --:--:-- 48623
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    s9110.tar.Z ... FAILED
==> **ERROR: One or more files did not pass the validity check!
Install aim9  failed**

How do I fix this?

Thanks

**Comment by xilabao** [comment]
Hi @Ankita-020696 , the official link is broken, you can modify the source link in  pkg/aim9/PKGBUILD

```
--- a/pkg/aim9/PKGBUILD
+++ b/pkg/aim9/PKGBUILD
@@ -4,7 +4,7 @@ pkgrel=1
 url='http://nchc.dl.sourceforge.net/project/aimbench/aim-suite9'
 arch=('i386' 'x86_64')
 license=('GPL')
-source=('http://nchc.dl.sourceforge.net/project/aimbench/aim-suite9/Initial%20release/s9110.tar.Z')
+source=('http://gentwo.org/benchmark/s9110.tar.Z')
```

**Comment by Ankita-020696** [comment]
> http://nchc.dl.sourceforge.net/project/aimbench/aim-suite9

Thank you
