### ISSUE TITLE
nr_threads becomes 0, rm 

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#88]
Hi,
I am getting following error, what could be the reason?
**$ lkp run ./hackbench-pipe-10-process-50%.yaml 
nr_threads becomes 0, rm 
Traceback (most recent call last):
	6: from /home/root/lkp/lkp-tests/bin/run-local:131:in `<main>'
	5: from /home/root/lkp/lkp-tests/lib/job.rb:691:in `expand_params'
	4: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `for_each_in'
	3: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `each'
	2: from /home/root/lkp/lkp-tests/lib/job.rb:78:in `block in for_each_in'
	1: from /home/root/lkp/lkp-tests/lib/job.rb:694:in `block in expand_params'
/home/root/lkp/lkp-tests/lib/job.rb:669:in `run_filter': /home/root/lkp/lkp-tests/filters/nr_threads: exitstatus 2 (Job::ParamError)**

Thanks

**Comment by xilabao** [comment]
I can reproduce it if I changed "nr_threads: 50%" to "nr_threads:", could you check the item in the file? @Ankita-020696 
```
# grep -C1 nr_threads ./hackbench-pipe-10-process-50%.yaml
disable_latency_stats: 1
nr_threads:
iterations: 10
# lkp run ./hackbench-pipe-10-process-50%.yaml
nr_threads becomes 0, rm
/root/lkp-tests/lib/job.rb:665:in `run_filter': /root/lkp-tests/filters/nr_threads: exitstatus 2 (Job::ParamError)
        from /root/lkp-tests/lib/job.rb:690:in `block in expand_params'
        from /root/lkp-tests/lib/job.rb:79:in `block in for_each_in'
        from /root/lkp-tests/lib/job.rb:78:in `each'
        from /root/lkp-tests/lib/job.rb:78:in `for_each_in'
        from /root/lkp-tests/lib/job.rb:687:in `expand_params'
        from /root/lkp-tests/bin/run-local:131:in `<main>'
```

**Comment by Ankita-020696** [comment]
> lkp run ./hackbench-pipe-10-process-50%.yaml

I have "nr_threads: 50%" still facing this error. 

```
lkp-tests# grep -C1 nr_threads ./hackbench-pipe-10-process-50%.yaml
disable_latency_stats: 1
nr_threads: 50%
iterations: 10

```

**Comment by xilabao** [comment]
could you run the below command and upload the result? btw, are you using the latest code?
```
lkp-tests# ruby -e "require \"#{ENV['PWD']}/lib/job\"; require \"#{ENV['PWD']}/lib/job2sh\"; job = Job.new; job.load(\"#{ENV['PWD']}/hackbench-pipe-10-process-50%.yaml\"); puts job['nr_threads']; Job2sh.new(job.to_hash).expand_params"
50%
```

**Comment by Ankita-020696** [comment]
```
lkp-tests# ruby -e "require \"#{ENV['PWD']}/lib/job\"; require \"#{ENV['PWD']}/lib/job2sh\"; job = Job.new; job.load(\"#{ENV['PWD']}/hackbench-pipe-10-process-50%.yaml\"); puts job['nr_threads'];Job2sh.new(job.to_hash).expand_params" 50%
50%

nr_threads becomes 0, rm 
Traceback (most recent call last):
	6: from -e:1:in `<main>'
	5: from /home/root/lkp/lkp-tests/lib/job.rb:691:in `expand_params'
	4: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `for_each_in'
	3: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `each'
	2: from /home/root/lkp/lkp-tests/lib/job.rb:78:in `block in for_each_in'
	1: from /home/root/lkp/lkp-tests/lib/job.rb:694:in `block in expand_params'
/home/root/lkp/lkp-tests/lib/job.rb:669:in `run_filter': /home/root/lkp/lkp-tests/filters/nr_threads: exitstatus 2 (Job::ParamError)

```

**Comment by Ankita-020696** [comment]
> could you run the below command and upload the result? btw, are you using the latest code?
> 
> ```
> lkp-tests# ruby -e "require \"#{ENV['PWD']}/lib/job\"; require \"#{ENV['PWD']}/lib/job2sh\"; job = Job.new; job.load(\"#{ENV['PWD']}/hackbench-pipe-10-process-50%.yaml\"); puts job['nr_threads']; Job2sh.new(job.to_hash).expand_params"
> 50%
> ```
Yes I am using latest code.
```
lkp-tests# ruby -e "require \"#{ENV['PWD']}/lib/job\"; require \"#{ENV['PWD']}/lib/job2sh\"; job = Job.new; job.load(\"#{ENV['PWD']}/hackbench-pipe-10-process-50%.yaml\"); puts job['nr_threads'];Job2sh.new(job.to_hash).expand_params" 50%
50%

nr_threads becomes 0, rm 
Traceback (most recent call last):
	6: from -e:1:in `<main>'
	5: from /home/root/lkp/lkp-tests/lib/job.rb:691:in `expand_params'
	4: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `for_each_in'
	3: from /home/root/lkp/lkp-tests/lib/job.rb:77:in `each'
	2: from /home/root/lkp/lkp-tests/lib/job.rb:78:in `block in for_each_in'
	1: from /home/root/lkp/lkp-tests/lib/job.rb:694:in `block in expand_params'
/home/root/lkp/lkp-tests/lib/job.rb:669:in `run_filter': /home/root/lkp/lkp-tests/filters/nr_threads: exitstatus 2 (Job::ParamError)

```

**Comment by xilabao** [comment]
@Ankita-020696 nr_threads can't be 50% if the cpu number < 2, I guess the cpu number in your environment is 1.
```
# nr_threads is 4 if the default value is 50%
$ nproc
8
```

**Comment by Ankita-020696** [comment]
> @Ankita-020696 nr_threads can't be 50% if the cpu number < 2, I guess the cpu number in your environment is 1.
> 
> ```
> # nr_threads is 4 if the default value is 50%
> $ nproc
> 8
> ```

Thanks
